from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    AccessReasonIn: t.typedef = ...
    AccessReasonOut: t.typedef = ...
    ApproveApprovalRequestMessageIn: t.typedef = ...
    ApproveApprovalRequestMessageOut: t.typedef = ...
    AccessLocationsIn: t.typedef = ...
    AccessLocationsOut: t.typedef = ...
    DismissApprovalRequestMessageIn: t.typedef = ...
    DismissApprovalRequestMessageOut: t.typedef = ...
    SignatureInfoIn: t.typedef = ...
    SignatureInfoOut: t.typedef = ...
    ApproveDecisionIn: t.typedef = ...
    ApproveDecisionOut: t.typedef = ...
    DismissDecisionIn: t.typedef = ...
    DismissDecisionOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    AccessApprovalSettingsIn: t.typedef = ...
    AccessApprovalSettingsOut: t.typedef = ...
    AccessApprovalServiceAccountIn: t.typedef = ...
    AccessApprovalServiceAccountOut: t.typedef = ...
    ListApprovalRequestsResponseIn: t.typedef = ...
    ListApprovalRequestsResponseOut: t.typedef = ...
    ResourcePropertiesIn: t.typedef = ...
    ResourcePropertiesOut: t.typedef = ...
    InvalidateApprovalRequestMessageIn: t.typedef = ...
    InvalidateApprovalRequestMessageOut: t.typedef = ...
    ApprovalRequestIn: t.typedef = ...
    ApprovalRequestOut: t.typedef = ...
    EnrolledServiceIn: t.typedef = ...
    EnrolledServiceOut: t.typedef = ...

class FuncList:
    projectsGetServiceAccount: t.func = ...
    projectsGetAccessApprovalSettings: t.func = ...
    projectsUpdateAccessApprovalSettings: t.func = ...
    projectsDeleteAccessApprovalSettings: t.func = ...
    projectsApprovalRequestsGet: t.func = ...
    projectsApprovalRequestsApprove: t.func = ...
    projectsApprovalRequestsDismiss: t.func = ...
    projectsApprovalRequestsList: t.func = ...
    projectsApprovalRequestsInvalidate: t.func = ...
    foldersUpdateAccessApprovalSettings: t.func = ...
    foldersDeleteAccessApprovalSettings: t.func = ...
    foldersGetAccessApprovalSettings: t.func = ...
    foldersGetServiceAccount: t.func = ...
    foldersApprovalRequestsGet: t.func = ...
    foldersApprovalRequestsDismiss: t.func = ...
    foldersApprovalRequestsInvalidate: t.func = ...
    foldersApprovalRequestsApprove: t.func = ...
    foldersApprovalRequestsList: t.func = ...
    organizationsDeleteAccessApprovalSettings: t.func = ...
    organizationsGetServiceAccount: t.func = ...
    organizationsGetAccessApprovalSettings: t.func = ...
    organizationsUpdateAccessApprovalSettings: t.func = ...
    organizationsApprovalRequestsGet: t.func = ...
    organizationsApprovalRequestsInvalidate: t.func = ...
    organizationsApprovalRequestsApprove: t.func = ...
    organizationsApprovalRequestsList: t.func = ...
    organizationsApprovalRequestsDismiss: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_accessapproval() -> Import: ...
