from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    NestedParameterIn: t.typedef = ...
    NestedParameterOut: t.typedef = ...
    ChannelIn: t.typedef = ...
    ChannelOut: t.typedef = ...
    UsageReportsIn: t.typedef = ...
    UsageReportsOut: t.typedef = ...
    ActivitiesIn: t.typedef = ...
    ActivitiesOut: t.typedef = ...
    ActivityIn: t.typedef = ...
    ActivityOut: t.typedef = ...
    UsageReportIn: t.typedef = ...
    UsageReportOut: t.typedef = ...

class FuncList:
    entityUsageReportsGet: t.func = ...
    customerUsageReportsGet: t.func = ...
    userUsageReportGet: t.func = ...
    channelsStop: t.func = ...
    activitiesWatch: t.func = ...
    activitiesList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_admin() -> Import: ...
