from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    ListOrgDataExchangesResponseIn: t.typedef = ...
    ListOrgDataExchangesResponseOut: t.typedef = ...
    GetPolicyOptionsIn: t.typedef = ...
    GetPolicyOptionsOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    DataProviderIn: t.typedef = ...
    DataProviderOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    GetIamPolicyRequestIn: t.typedef = ...
    GetIamPolicyRequestOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    ListDataExchangesResponseIn: t.typedef = ...
    ListDataExchangesResponseOut: t.typedef = ...
    ListListingsResponseIn: t.typedef = ...
    ListListingsResponseOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    DestinationDatasetReferenceIn: t.typedef = ...
    DestinationDatasetReferenceOut: t.typedef = ...
    SubscribeListingResponseIn: t.typedef = ...
    SubscribeListingResponseOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    DataExchangeIn: t.typedef = ...
    DataExchangeOut: t.typedef = ...
    BigQueryDatasetSourceIn: t.typedef = ...
    BigQueryDatasetSourceOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    ListingIn: t.typedef = ...
    ListingOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    SubscribeListingRequestIn: t.typedef = ...
    SubscribeListingRequestOut: t.typedef = ...
    DestinationDatasetIn: t.typedef = ...
    DestinationDatasetOut: t.typedef = ...
    PublisherIn: t.typedef = ...
    PublisherOut: t.typedef = ...

class FuncList:
    organizationsLocationsDataExchangesList: t.func = ...
    projectsLocationsDataExchangesList: t.func = ...
    projectsLocationsDataExchangesGet: t.func = ...
    projectsLocationsDataExchangesSetIamPolicy: t.func = ...
    projectsLocationsDataExchangesCreate: t.func = ...
    projectsLocationsDataExchangesDelete: t.func = ...
    projectsLocationsDataExchangesTestIamPermissions: t.func = ...
    projectsLocationsDataExchangesPatch: t.func = ...
    projectsLocationsDataExchangesGetIamPolicy: t.func = ...
    projectsLocationsDataExchangesListingsCreate: t.func = ...
    projectsLocationsDataExchangesListingsTestIamPermissions: t.func = ...
    projectsLocationsDataExchangesListingsList: t.func = ...
    projectsLocationsDataExchangesListingsDelete: t.func = ...
    projectsLocationsDataExchangesListingsSubscribe: t.func = ...
    projectsLocationsDataExchangesListingsSetIamPolicy: t.func = ...
    projectsLocationsDataExchangesListingsGet: t.func = ...
    projectsLocationsDataExchangesListingsGetIamPolicy: t.func = ...
    projectsLocationsDataExchangesListingsPatch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_analyticshub() -> Import: ...
