from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    ConnectionIn: t.typedef = ...
    ConnectionOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    GetPolicyOptionsIn: t.typedef = ...
    GetPolicyOptionsOut: t.typedef = ...
    ListConnectionsResponseIn: t.typedef = ...
    ListConnectionsResponseOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    CloudSqlCredentialIn: t.typedef = ...
    CloudSqlCredentialOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    CloudSqlPropertiesIn: t.typedef = ...
    CloudSqlPropertiesOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    ConnectionCredentialIn: t.typedef = ...
    ConnectionCredentialOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    GetIamPolicyRequestIn: t.typedef = ...
    GetIamPolicyRequestOut: t.typedef = ...

class FuncList:
    projectsLocationsConnectionsDelete: t.func = ...
    projectsLocationsConnectionsGet: t.func = ...
    projectsLocationsConnectionsList: t.func = ...
    projectsLocationsConnectionsPatch: t.func = ...
    projectsLocationsConnectionsTestIamPermissions: t.func = ...
    projectsLocationsConnectionsCreate: t.func = ...
    projectsLocationsConnectionsSetIamPolicy: t.func = ...
    projectsLocationsConnectionsUpdateCredential: t.func = ...
    projectsLocationsConnectionsGetIamPolicy: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_bigqueryconnection() -> Import: ...
