from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleTypeDateIn: t.typedef = ...
    GoogleTypeDateOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1BudgetIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1BudgetOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1CustomPeriodIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1CustomPeriodOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1NotificationsRuleIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1NotificationsRuleOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1LastPeriodAmountIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1LastPeriodAmountOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1FilterIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1FilterOut: t.typedef = ...
    GoogleTypeMoneyIn: t.typedef = ...
    GoogleTypeMoneyOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1BudgetAmountIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1BudgetAmountOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1ThresholdRuleIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1ThresholdRuleOut: t.typedef = ...
    GoogleCloudBillingBudgetsV1ListBudgetsResponseIn: t.typedef = ...
    GoogleCloudBillingBudgetsV1ListBudgetsResponseOut: t.typedef = ...

class FuncList:
    billingAccountsBudgetsGet: t.func = ...
    billingAccountsBudgetsList: t.func = ...
    billingAccountsBudgetsDelete: t.func = ...
    billingAccountsBudgetsCreate: t.func = ...
    billingAccountsBudgetsPatch: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_billingbudgets() -> Import: ...
