from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    EthereumEndpointsIn: t.typedef = ...
    EthereumEndpointsOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    BlockchainNodeIn: t.typedef = ...
    BlockchainNodeOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    GethDetailsIn: t.typedef = ...
    GethDetailsOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    ListBlockchainNodesResponseIn: t.typedef = ...
    ListBlockchainNodesResponseOut: t.typedef = ...
    EndpointInfoIn: t.typedef = ...
    EndpointInfoOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    EthereumDetailsIn: t.typedef = ...
    EthereumDetailsOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    ConnectionInfoIn: t.typedef = ...
    ConnectionInfoOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsBlockchainNodesPatch: t.func = ...
    projectsLocationsBlockchainNodesCreate: t.func = ...
    projectsLocationsBlockchainNodesDelete: t.func = ...
    projectsLocationsBlockchainNodesList: t.func = ...
    projectsLocationsBlockchainNodesGet: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_blockchainnodeengine() -> Import: ...
