from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    BlogIn: t.typedef = ...
    BlogOut: t.typedef = ...
    UserIn: t.typedef = ...
    UserOut: t.typedef = ...
    BlogListIn: t.typedef = ...
    BlogListOut: t.typedef = ...
    CommentListIn: t.typedef = ...
    CommentListOut: t.typedef = ...
    BlogPerUserInfoIn: t.typedef = ...
    BlogPerUserInfoOut: t.typedef = ...
    PageviewsIn: t.typedef = ...
    PageviewsOut: t.typedef = ...
    PostUserInfoIn: t.typedef = ...
    PostUserInfoOut: t.typedef = ...
    PostIn: t.typedef = ...
    PostOut: t.typedef = ...
    BlogUserInfoIn: t.typedef = ...
    BlogUserInfoOut: t.typedef = ...
    PostListIn: t.typedef = ...
    PostListOut: t.typedef = ...
    CommentIn: t.typedef = ...
    CommentOut: t.typedef = ...
    PostUserInfosListIn: t.typedef = ...
    PostUserInfosListOut: t.typedef = ...
    PostPerUserInfoIn: t.typedef = ...
    PostPerUserInfoOut: t.typedef = ...
    PageListIn: t.typedef = ...
    PageListOut: t.typedef = ...
    PageIn: t.typedef = ...
    PageOut: t.typedef = ...

class FuncList:
    blogUserInfosGet: t.func = ...
    postUserInfosList: t.func = ...
    postUserInfosGet: t.func = ...
    postsUpdate: t.func = ...
    postsSearch: t.func = ...
    postsGet: t.func = ...
    postsList: t.func = ...
    postsDelete: t.func = ...
    postsGetByPath: t.func = ...
    postsInsert: t.func = ...
    postsPatch: t.func = ...
    postsRevert: t.func = ...
    postsPublish: t.func = ...
    usersGet: t.func = ...
    pageViewsGet: t.func = ...
    commentsApprove: t.func = ...
    commentsDelete: t.func = ...
    commentsGet: t.func = ...
    commentsList: t.func = ...
    commentsRemoveContent: t.func = ...
    commentsListByBlog: t.func = ...
    commentsMarkAsSpam: t.func = ...
    blogsGet: t.func = ...
    blogsListByUser: t.func = ...
    blogsGetByUrl: t.func = ...
    pagesPatch: t.func = ...
    pagesDelete: t.func = ...
    pagesRevert: t.func = ...
    pagesGet: t.func = ...
    pagesPublish: t.func = ...
    pagesList: t.func = ...
    pagesInsert: t.func = ...
    pagesUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_blogger() -> Import: ...
