from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TimeSeriesIn: t.typedef = ...
    TimeSeriesOut: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    DailySubEntityTypeIn: t.typedef = ...
    DailySubEntityTypeOut: t.typedef = ...
    DatedValueIn: t.typedef = ...
    DatedValueOut: t.typedef = ...
    GetDailyMetricsTimeSeriesResponseIn: t.typedef = ...
    GetDailyMetricsTimeSeriesResponseOut: t.typedef = ...
    DailyMetricTimeSeriesIn: t.typedef = ...
    DailyMetricTimeSeriesOut: t.typedef = ...
    SearchKeywordCountIn: t.typedef = ...
    SearchKeywordCountOut: t.typedef = ...
    FetchMultiDailyMetricsTimeSeriesResponseIn: t.typedef = ...
    FetchMultiDailyMetricsTimeSeriesResponseOut: t.typedef = ...
    InsightsValueIn: t.typedef = ...
    InsightsValueOut: t.typedef = ...
    ListSearchKeywordImpressionsMonthlyResponseIn: t.typedef = ...
    ListSearchKeywordImpressionsMonthlyResponseOut: t.typedef = ...
    MultiDailyMetricTimeSeriesIn: t.typedef = ...
    MultiDailyMetricTimeSeriesOut: t.typedef = ...
    TimeOfDayIn: t.typedef = ...
    TimeOfDayOut: t.typedef = ...

class FuncList:
    locationsGetDailyMetricsTimeSeries: t.func = ...
    locationsFetchMultiDailyMetricsTimeSeries: t.func = ...
    locationsSearchkeywordsImpressionsMonthlyList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_businessprofileperformance() -> Import: ...
