from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    PolicyDataTypeAnnotationIn: t.typedef = ...
    PolicyDataTypeAnnotationOut: t.typedef = ...
    PolicyPurposeOfUseAnnotationIn: t.typedef = ...
    PolicyPurposeOfUseAnnotationOut: t.typedef = ...
    AnalyzePrivacyPolicyRequestIn: t.typedef = ...
    AnalyzePrivacyPolicyRequestOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    PolicySectionAnnotationIn: t.typedef = ...
    PolicySectionAnnotationOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    AnalyzePrivacyPolicyResponseIn: t.typedef = ...
    AnalyzePrivacyPolicyResponseOut: t.typedef = ...
    LastUpdatedDateIn: t.typedef = ...
    LastUpdatedDateOut: t.typedef = ...

class FuncList:
    privacypolicyAnalyze: t.func = ...
    accountsAppsOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_checks() -> Import: ...
