from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    PubsubTargetIn: t.typedef = ...
    PubsubTargetOut: t.typedef = ...
    JobIn: t.typedef = ...
    JobOut: t.typedef = ...
    RunJobRequestIn: t.typedef = ...
    RunJobRequestOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    RetryConfigIn: t.typedef = ...
    RetryConfigOut: t.typedef = ...
    AppEngineRoutingIn: t.typedef = ...
    AppEngineRoutingOut: t.typedef = ...
    PauseJobRequestIn: t.typedef = ...
    PauseJobRequestOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    OAuthTokenIn: t.typedef = ...
    OAuthTokenOut: t.typedef = ...
    HttpTargetIn: t.typedef = ...
    HttpTargetOut: t.typedef = ...
    PubsubMessageIn: t.typedef = ...
    PubsubMessageOut: t.typedef = ...
    ListJobsResponseIn: t.typedef = ...
    ListJobsResponseOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ResumeJobRequestIn: t.typedef = ...
    ResumeJobRequestOut: t.typedef = ...
    OidcTokenIn: t.typedef = ...
    OidcTokenOut: t.typedef = ...
    AppEngineHttpTargetIn: t.typedef = ...
    AppEngineHttpTargetOut: t.typedef = ...

class FuncList:
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsJobsPause: t.func = ...
    projectsLocationsJobsGet: t.func = ...
    projectsLocationsJobsList: t.func = ...
    projectsLocationsJobsCreate: t.func = ...
    projectsLocationsJobsDelete: t.func = ...
    projectsLocationsJobsPatch: t.func = ...
    projectsLocationsJobsRun: t.func = ...
    projectsLocationsJobsResume: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_cloudscheduler() -> Import: ...
