from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ContentTypeInfoIn: t.typedef = ...
    ContentTypeInfoOut: t.typedef = ...
    CloseCaseRequestIn: t.typedef = ...
    CloseCaseRequestOut: t.typedef = ...
    CaseClassificationIn: t.typedef = ...
    CaseClassificationOut: t.typedef = ...
    ActorIn: t.typedef = ...
    ActorOut: t.typedef = ...
    DiffUploadResponseIn: t.typedef = ...
    DiffUploadResponseOut: t.typedef = ...
    SearchCaseClassificationsResponseIn: t.typedef = ...
    SearchCaseClassificationsResponseOut: t.typedef = ...
    DiffUploadRequestIn: t.typedef = ...
    DiffUploadRequestOut: t.typedef = ...
    DiffVersionResponseIn: t.typedef = ...
    DiffVersionResponseOut: t.typedef = ...
    CommentIn: t.typedef = ...
    CommentOut: t.typedef = ...
    ObjectIdIn: t.typedef = ...
    ObjectIdOut: t.typedef = ...
    CaseIn: t.typedef = ...
    CaseOut: t.typedef = ...
    EscalationIn: t.typedef = ...
    EscalationOut: t.typedef = ...
    Blobstore2InfoIn: t.typedef = ...
    Blobstore2InfoOut: t.typedef = ...
    ListCommentsResponseIn: t.typedef = ...
    ListCommentsResponseOut: t.typedef = ...
    EscalateCaseRequestIn: t.typedef = ...
    EscalateCaseRequestOut: t.typedef = ...
    MediaIn: t.typedef = ...
    MediaOut: t.typedef = ...
    DiffChecksumsResponseIn: t.typedef = ...
    DiffChecksumsResponseOut: t.typedef = ...
    CompositeMediaIn: t.typedef = ...
    CompositeMediaOut: t.typedef = ...
    DiffDownloadResponseIn: t.typedef = ...
    DiffDownloadResponseOut: t.typedef = ...
    SearchCasesResponseIn: t.typedef = ...
    SearchCasesResponseOut: t.typedef = ...
    ListCasesResponseIn: t.typedef = ...
    ListCasesResponseOut: t.typedef = ...
    ListAttachmentsResponseIn: t.typedef = ...
    ListAttachmentsResponseOut: t.typedef = ...
    DownloadParametersIn: t.typedef = ...
    DownloadParametersOut: t.typedef = ...
    CreateAttachmentRequestIn: t.typedef = ...
    CreateAttachmentRequestOut: t.typedef = ...
    AttachmentIn: t.typedef = ...
    AttachmentOut: t.typedef = ...
    WorkflowOperationMetadataIn: t.typedef = ...
    WorkflowOperationMetadataOut: t.typedef = ...

class FuncList:
    caseClassificationsSearch: t.func = ...
    casesPatch: t.func = ...
    casesCreate: t.func = ...
    casesClose: t.func = ...
    casesSearch: t.func = ...
    casesList: t.func = ...
    casesEscalate: t.func = ...
    casesGet: t.func = ...
    casesCommentsList: t.func = ...
    casesCommentsCreate: t.func = ...
    casesAttachmentsList: t.func = ...
    mediaDownload: t.func = ...
    mediaUpload: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_cloudsupport() -> Import: ...
