from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TimedCountIn: t.typedef = ...
    TimedCountOut: t.typedef = ...
    ErrorEventIn: t.typedef = ...
    ErrorEventOut: t.typedef = ...
    ErrorGroupIn: t.typedef = ...
    ErrorGroupOut: t.typedef = ...
    ListGroupStatsResponseIn: t.typedef = ...
    ListGroupStatsResponseOut: t.typedef = ...
    ServiceContextIn: t.typedef = ...
    ServiceContextOut: t.typedef = ...
    SourceLocationIn: t.typedef = ...
    SourceLocationOut: t.typedef = ...
    SourceReferenceIn: t.typedef = ...
    SourceReferenceOut: t.typedef = ...
    DeleteEventsResponseIn: t.typedef = ...
    DeleteEventsResponseOut: t.typedef = ...
    TrackingIssueIn: t.typedef = ...
    TrackingIssueOut: t.typedef = ...
    HttpRequestContextIn: t.typedef = ...
    HttpRequestContextOut: t.typedef = ...
    ReportedErrorEventIn: t.typedef = ...
    ReportedErrorEventOut: t.typedef = ...
    ErrorContextIn: t.typedef = ...
    ErrorContextOut: t.typedef = ...
    ReportErrorEventResponseIn: t.typedef = ...
    ReportErrorEventResponseOut: t.typedef = ...
    ErrorGroupStatsIn: t.typedef = ...
    ErrorGroupStatsOut: t.typedef = ...
    ListEventsResponseIn: t.typedef = ...
    ListEventsResponseOut: t.typedef = ...

class FuncList:
    projectsDeleteEvents: t.func = ...
    projectsGroupStatsList: t.func = ...
    projectsEventsReport: t.func = ...
    projectsEventsList: t.func = ...
    projectsGroupsGet: t.func = ...
    projectsGroupsUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_clouderrorreporting() -> Import: ...
