from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    RemovePublicKeyRequestIn: t.typedef = ...
    RemovePublicKeyRequestOut: t.typedef = ...
    EnvironmentIn: t.typedef = ...
    EnvironmentOut: t.typedef = ...
    RemovePublicKeyResponseIn: t.typedef = ...
    RemovePublicKeyResponseOut: t.typedef = ...
    AuthorizeEnvironmentRequestIn: t.typedef = ...
    AuthorizeEnvironmentRequestOut: t.typedef = ...
    AddPublicKeyRequestIn: t.typedef = ...
    AddPublicKeyRequestOut: t.typedef = ...
    CreateEnvironmentMetadataIn: t.typedef = ...
    CreateEnvironmentMetadataOut: t.typedef = ...
    StartEnvironmentMetadataIn: t.typedef = ...
    StartEnvironmentMetadataOut: t.typedef = ...
    DeleteEnvironmentMetadataIn: t.typedef = ...
    DeleteEnvironmentMetadataOut: t.typedef = ...
    RemovePublicKeyMetadataIn: t.typedef = ...
    RemovePublicKeyMetadataOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    StartEnvironmentRequestIn: t.typedef = ...
    StartEnvironmentRequestOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    AddPublicKeyMetadataIn: t.typedef = ...
    AddPublicKeyMetadataOut: t.typedef = ...
    StartEnvironmentResponseIn: t.typedef = ...
    StartEnvironmentResponseOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    AuthorizeEnvironmentResponseIn: t.typedef = ...
    AuthorizeEnvironmentResponseOut: t.typedef = ...
    AddPublicKeyResponseIn: t.typedef = ...
    AddPublicKeyResponseOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    AuthorizeEnvironmentMetadataIn: t.typedef = ...
    AuthorizeEnvironmentMetadataOut: t.typedef = ...

class FuncList:
    usersEnvironmentsAddPublicKey: t.func = ...
    usersEnvironmentsRemovePublicKey: t.func = ...
    usersEnvironmentsGet: t.func = ...
    usersEnvironmentsStart: t.func = ...
    usersEnvironmentsAuthorize: t.func = ...
    operationsCancel: t.func = ...
    operationsGet: t.func = ...
    operationsList: t.func = ...
    operationsDelete: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_cloudshell() -> Import: ...
