from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    DebuggeeIn: t.typedef = ...
    DebuggeeOut: t.typedef = ...
    BreakpointIn: t.typedef = ...
    BreakpointOut: t.typedef = ...
    CloudWorkspaceIdIn: t.typedef = ...
    CloudWorkspaceIdOut: t.typedef = ...
    UpdateActiveBreakpointRequestIn: t.typedef = ...
    UpdateActiveBreakpointRequestOut: t.typedef = ...
    SourceLocationIn: t.typedef = ...
    SourceLocationOut: t.typedef = ...
    SetBreakpointResponseIn: t.typedef = ...
    SetBreakpointResponseOut: t.typedef = ...
    RegisterDebuggeeResponseIn: t.typedef = ...
    RegisterDebuggeeResponseOut: t.typedef = ...
    ListActiveBreakpointsResponseIn: t.typedef = ...
    ListActiveBreakpointsResponseOut: t.typedef = ...
    CloudWorkspaceSourceContextIn: t.typedef = ...
    CloudWorkspaceSourceContextOut: t.typedef = ...
    RegisterDebuggeeRequestIn: t.typedef = ...
    RegisterDebuggeeRequestOut: t.typedef = ...
    ListDebuggeesResponseIn: t.typedef = ...
    ListDebuggeesResponseOut: t.typedef = ...
    SourceContextIn: t.typedef = ...
    SourceContextOut: t.typedef = ...
    UpdateActiveBreakpointResponseIn: t.typedef = ...
    UpdateActiveBreakpointResponseOut: t.typedef = ...
    ProjectRepoIdIn: t.typedef = ...
    ProjectRepoIdOut: t.typedef = ...
    StackFrameIn: t.typedef = ...
    StackFrameOut: t.typedef = ...
    ListBreakpointsResponseIn: t.typedef = ...
    ListBreakpointsResponseOut: t.typedef = ...
    VariableIn: t.typedef = ...
    VariableOut: t.typedef = ...
    CloudRepoSourceContextIn: t.typedef = ...
    CloudRepoSourceContextOut: t.typedef = ...
    RepoIdIn: t.typedef = ...
    RepoIdOut: t.typedef = ...
    StatusMessageIn: t.typedef = ...
    StatusMessageOut: t.typedef = ...
    GitSourceContextIn: t.typedef = ...
    GitSourceContextOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ExtendedSourceContextIn: t.typedef = ...
    ExtendedSourceContextOut: t.typedef = ...
    AliasContextIn: t.typedef = ...
    AliasContextOut: t.typedef = ...
    GetBreakpointResponseIn: t.typedef = ...
    GetBreakpointResponseOut: t.typedef = ...
    FormatMessageIn: t.typedef = ...
    FormatMessageOut: t.typedef = ...
    GerritSourceContextIn: t.typedef = ...
    GerritSourceContextOut: t.typedef = ...

class FuncList:
    debuggerDebuggeesList: t.func = ...
    debuggerDebuggeesBreakpointsGet: t.func = ...
    debuggerDebuggeesBreakpointsList: t.func = ...
    debuggerDebuggeesBreakpointsSet: t.func = ...
    debuggerDebuggeesBreakpointsDelete: t.func = ...
    controllerDebuggeesRegister: t.func = ...
    controllerDebuggeesBreakpointsList: t.func = ...
    controllerDebuggeesBreakpointsUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_clouddebugger() -> Import: ...
