from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ListEntityTypesResponseIn: t.typedef = ...
    ListEntityTypesResponseOut: t.typedef = ...
    InputParameterIn: t.typedef = ...
    InputParameterOut: t.typedef = ...
    ExecuteSqlQueryRequestIn: t.typedef = ...
    ExecuteSqlQueryRequestOut: t.typedef = ...
    ListActionsResponseIn: t.typedef = ...
    ListActionsResponseOut: t.typedef = ...
    EntityIn: t.typedef = ...
    EntityOut: t.typedef = ...
    ActionIn: t.typedef = ...
    ActionOut: t.typedef = ...
    ResultMetadataIn: t.typedef = ...
    ResultMetadataOut: t.typedef = ...
    FieldIn: t.typedef = ...
    FieldOut: t.typedef = ...
    ExecuteSqlQueryResponseIn: t.typedef = ...
    ExecuteSqlQueryResponseOut: t.typedef = ...
    ExecuteActionResponseIn: t.typedef = ...
    ExecuteActionResponseOut: t.typedef = ...
    ListEntitiesResponseIn: t.typedef = ...
    ListEntitiesResponseOut: t.typedef = ...
    UpdateEntitiesWithConditionsResponseIn: t.typedef = ...
    UpdateEntitiesWithConditionsResponseOut: t.typedef = ...
    EntityTypeIn: t.typedef = ...
    EntityTypeOut: t.typedef = ...
    ReferenceIn: t.typedef = ...
    ReferenceOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ExecuteActionRequestIn: t.typedef = ...
    ExecuteActionRequestOut: t.typedef = ...
    QueryIn: t.typedef = ...
    QueryOut: t.typedef = ...

class FuncList:
    projectsLocationsConnectionsExecuteSqlQuery: t.func = ...
    projectsLocationsConnectionsEntityTypesList: t.func = ...
    projectsLocationsConnectionsEntityTypesEntitiesCreate: t.func = ...
    projectsLocationsConnectionsEntityTypesEntitiesUpdateEntitiesWithConditions: t.func = (
        ...
    )
    projectsLocationsConnectionsEntityTypesEntitiesGet: t.func = ...
    projectsLocationsConnectionsEntityTypesEntitiesDeleteEntitiesWithConditions: t.func = (
        ...
    )
    projectsLocationsConnectionsEntityTypesEntitiesList: t.func = ...
    projectsLocationsConnectionsEntityTypesEntitiesDelete: t.func = ...
    projectsLocationsConnectionsEntityTypesEntitiesPatch: t.func = ...
    projectsLocationsConnectionsActionsExecute: t.func = ...
    projectsLocationsConnectionsActionsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_connectors() -> Import: ...
