from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleApiHttpBodyIn: t.typedef = ...
    GoogleApiHttpBodyOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaDocumentIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaDocumentOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaMediaInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaMediaInfoOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsRequestInlineSourceIn: t.typedef = (
        ...
    )
    GoogleCloudDiscoveryengineV1betaImportDocumentsRequestInlineSourceOut: t.typedef = (
        ...
    )
    GoogleCloudDiscoveryengineV1betaPageInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPageInfoOut: t.typedef = ...
    GoogleTypeDateIn: t.typedef = ...
    GoogleTypeDateOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaPurgeDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaPurgeDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportDocumentsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportDocumentsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaDocumentInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaDocumentInfoOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaCustomAttributeIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaCustomAttributeOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsRequestIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsRequestOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsRequestIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsRequestOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaUserEventIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaUserEventOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportUserEventsMetadataIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportUserEventsMetadataOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPurgeDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPurgeDocumentsMetadataOut: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingServiceContextIn: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingServiceContextOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsRequestInlineSourceIn: t.typedef = (
        ...
    )
    GoogleCloudDiscoveryengineV1betaImportUserEventsRequestInlineSourceOut: t.typedef = (
        ...
    )
    GoogleCloudDiscoveryengineLoggingHttpRequestContextIn: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingHttpRequestContextOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaSearchInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaSearchInfoOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaGcsSourceIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaGcsSourceOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportDocumentsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPanelInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPanelInfoOut: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingSourceLocationIn: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingSourceLocationOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaRecommendResponseRecommendationResultIn: t.typedef = (
        ...
    )
    GoogleCloudDiscoveryengineV1betaRecommendResponseRecommendationResultOut: t.typedef = (
        ...
    )
    GoogleCloudDiscoveryengineV1betaSchemaIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaSchemaOut: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingErrorLogIn: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingErrorLogOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaListDocumentsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaListDocumentsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportErrorConfigIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportErrorConfigOut: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingErrorContextIn: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingErrorContextOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaUserInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaUserInfoOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPurgeDocumentsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPurgeDocumentsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingImportErrorContextIn: t.typedef = ...
    GoogleCloudDiscoveryengineLoggingImportErrorContextOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaCompletionInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaCompletionInfoOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaRecommendRequestIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaRecommendRequestOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaSchemaIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaSchemaOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaBigQuerySourceIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaBigQuerySourceOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportUserEventsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportUserEventsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportDocumentsMetadataIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportDocumentsMetadataOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportErrorConfigIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaImportErrorConfigOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaTransactionInfoIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaTransactionInfoOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaRecommendResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaRecommendResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaPurgeDocumentsResponseIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1alphaPurgeDocumentsResponseOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsMetadataIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaImportUserEventsMetadataOut: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPurgeDocumentsRequestIn: t.typedef = ...
    GoogleCloudDiscoveryengineV1betaPurgeDocumentsRequestOut: t.typedef = ...

class FuncList:
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsDataStoresOperationsGet: t.func = ...
    projectsLocationsDataStoresOperationsList: t.func = ...
    projectsLocationsDataStoresServingConfigsRecommend: t.func = ...
    projectsLocationsDataStoresModelsOperationsList: t.func = ...
    projectsLocationsDataStoresModelsOperationsGet: t.func = ...
    projectsLocationsDataStoresUserEventsImport: t.func = ...
    projectsLocationsDataStoresUserEventsWrite: t.func = ...
    projectsLocationsDataStoresUserEventsCollect: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsImport: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsGet: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsCreate: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsDelete: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsPurge: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsPatch: t.func = ...
    projectsLocationsDataStoresBranchesDocumentsList: t.func = ...
    projectsLocationsDataStoresBranchesOperationsGet: t.func = ...
    projectsLocationsDataStoresBranchesOperationsList: t.func = ...
    projectsLocationsCollectionsOperationsGet: t.func = ...
    projectsLocationsCollectionsOperationsList: t.func = ...
    projectsLocationsCollectionsDataStoresModelsOperationsList: t.func = ...
    projectsLocationsCollectionsDataStoresModelsOperationsGet: t.func = ...
    projectsLocationsCollectionsDataStoresOperationsList: t.func = ...
    projectsLocationsCollectionsDataStoresOperationsGet: t.func = ...
    projectsLocationsCollectionsDataStoresUserEventsCollect: t.func = ...
    projectsLocationsCollectionsDataStoresUserEventsWrite: t.func = ...
    projectsLocationsCollectionsDataStoresUserEventsImport: t.func = ...
    projectsLocationsCollectionsDataStoresServingConfigsRecommend: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsDelete: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsImport: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsCreate: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsPatch: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsList: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsPurge: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesDocumentsGet: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesOperationsGet: t.func = ...
    projectsLocationsCollectionsDataStoresBranchesOperationsList: t.func = ...
    projectsLocationsCollectionsEnginesOperationsGet: t.func = ...
    projectsLocationsCollectionsEnginesOperationsList: t.func = ...
    projectsOperationsList: t.func = ...
    projectsOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_discoveryengine() -> Import: ...
