from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    QueryScheduleIn: t.typedef = ...
    QueryScheduleOut: t.typedef = ...
    RunQueryRequestIn: t.typedef = ...
    RunQueryRequestOut: t.typedef = ...
    OptionsIn: t.typedef = ...
    OptionsOut: t.typedef = ...
    ReportKeyIn: t.typedef = ...
    ReportKeyOut: t.typedef = ...
    ReportStatusIn: t.typedef = ...
    ReportStatusOut: t.typedef = ...
    DisjunctiveMatchStatementIn: t.typedef = ...
    DisjunctiveMatchStatementOut: t.typedef = ...
    ListReportsResponseIn: t.typedef = ...
    ListReportsResponseOut: t.typedef = ...
    RuleIn: t.typedef = ...
    RuleOut: t.typedef = ...
    QueryIn: t.typedef = ...
    QueryOut: t.typedef = ...
    PathFilterIn: t.typedef = ...
    PathFilterOut: t.typedef = ...
    ChannelGroupingIn: t.typedef = ...
    ChannelGroupingOut: t.typedef = ...
    PathQueryOptionsIn: t.typedef = ...
    PathQueryOptionsOut: t.typedef = ...
    ParametersIn: t.typedef = ...
    ParametersOut: t.typedef = ...
    DateIn: t.typedef = ...
    DateOut: t.typedef = ...
    QueryMetadataIn: t.typedef = ...
    QueryMetadataOut: t.typedef = ...
    PathQueryOptionsFilterIn: t.typedef = ...
    PathQueryOptionsFilterOut: t.typedef = ...
    EventFilterIn: t.typedef = ...
    EventFilterOut: t.typedef = ...
    FilterPairIn: t.typedef = ...
    FilterPairOut: t.typedef = ...
    DataRangeIn: t.typedef = ...
    DataRangeOut: t.typedef = ...
    ListQueriesResponseIn: t.typedef = ...
    ListQueriesResponseOut: t.typedef = ...
    ReportMetadataIn: t.typedef = ...
    ReportMetadataOut: t.typedef = ...
    ReportIn: t.typedef = ...
    ReportOut: t.typedef = ...

class FuncList:
    queriesDelete: t.func = ...
    queriesRun: t.func = ...
    queriesList: t.func = ...
    queriesCreate: t.func = ...
    queriesGet: t.func = ...
    queriesReportsGet: t.func = ...
    queriesReportsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_doubleclickbidmanager() -> Import: ...
