from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ApnsFcmOptionsIn: t.typedef = ...
    ApnsFcmOptionsOut: t.typedef = ...
    ColorIn: t.typedef = ...
    ColorOut: t.typedef = ...
    FcmOptionsIn: t.typedef = ...
    FcmOptionsOut: t.typedef = ...
    NotificationIn: t.typedef = ...
    NotificationOut: t.typedef = ...
    LightSettingsIn: t.typedef = ...
    LightSettingsOut: t.typedef = ...
    AndroidNotificationIn: t.typedef = ...
    AndroidNotificationOut: t.typedef = ...
    SendMessageRequestIn: t.typedef = ...
    SendMessageRequestOut: t.typedef = ...
    WebpushConfigIn: t.typedef = ...
    WebpushConfigOut: t.typedef = ...
    AndroidFcmOptionsIn: t.typedef = ...
    AndroidFcmOptionsOut: t.typedef = ...
    MessageIn: t.typedef = ...
    MessageOut: t.typedef = ...
    AndroidConfigIn: t.typedef = ...
    AndroidConfigOut: t.typedef = ...
    WebpushFcmOptionsIn: t.typedef = ...
    WebpushFcmOptionsOut: t.typedef = ...
    ApnsConfigIn: t.typedef = ...
    ApnsConfigOut: t.typedef = ...

class FuncList:
    projectsMessagesSend: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_fcm() -> Import: ...
