from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TestRulesetRequestIn: t.typedef = ...
    TestRulesetRequestOut: t.typedef = ...
    FunctionMockIn: t.typedef = ...
    FunctionMockOut: t.typedef = ...
    IssueIn: t.typedef = ...
    IssueOut: t.typedef = ...
    RulesetIn: t.typedef = ...
    RulesetOut: t.typedef = ...
    SourcePositionIn: t.typedef = ...
    SourcePositionOut: t.typedef = ...
    SourceIn: t.typedef = ...
    SourceOut: t.typedef = ...
    GetReleaseExecutableResponseIn: t.typedef = ...
    GetReleaseExecutableResponseOut: t.typedef = ...
    ResultIn: t.typedef = ...
    ResultOut: t.typedef = ...
    TestCaseIn: t.typedef = ...
    TestCaseOut: t.typedef = ...
    TestSuiteIn: t.typedef = ...
    TestSuiteOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    FunctionCallIn: t.typedef = ...
    FunctionCallOut: t.typedef = ...
    TestRulesetResponseIn: t.typedef = ...
    TestRulesetResponseOut: t.typedef = ...
    ListReleasesResponseIn: t.typedef = ...
    ListReleasesResponseOut: t.typedef = ...
    MetadataIn: t.typedef = ...
    MetadataOut: t.typedef = ...
    ListRulesetsResponseIn: t.typedef = ...
    ListRulesetsResponseOut: t.typedef = ...
    VisitedExpressionIn: t.typedef = ...
    VisitedExpressionOut: t.typedef = ...
    FileIn: t.typedef = ...
    FileOut: t.typedef = ...
    UpdateReleaseRequestIn: t.typedef = ...
    UpdateReleaseRequestOut: t.typedef = ...
    ExpressionReportIn: t.typedef = ...
    ExpressionReportOut: t.typedef = ...
    TestResultIn: t.typedef = ...
    TestResultOut: t.typedef = ...
    ValueCountIn: t.typedef = ...
    ValueCountOut: t.typedef = ...
    ArgIn: t.typedef = ...
    ArgOut: t.typedef = ...
    ReleaseIn: t.typedef = ...
    ReleaseOut: t.typedef = ...

class FuncList:
    projectsTest: t.func = ...
    projectsReleasesGet: t.func = ...
    projectsReleasesList: t.func = ...
    projectsReleasesDelete: t.func = ...
    projectsReleasesPatch: t.func = ...
    projectsReleasesGetExecutable: t.func = ...
    projectsReleasesCreate: t.func = ...
    projectsRulesetsList: t.func = ...
    projectsRulesetsDelete: t.func = ...
    projectsRulesetsCreate: t.func = ...
    projectsRulesetsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_firebaserules() -> Import: ...
