from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SuffixIn: t.typedef = ...
    SuffixOut: t.typedef = ...
    SocialMetaTagInfoIn: t.typedef = ...
    SocialMetaTagInfoOut: t.typedef = ...
    CreateShortDynamicLinkResponseIn: t.typedef = ...
    CreateShortDynamicLinkResponseOut: t.typedef = ...
    IosInfoIn: t.typedef = ...
    IosInfoOut: t.typedef = ...
    DynamicLinkWarningIn: t.typedef = ...
    DynamicLinkWarningOut: t.typedef = ...
    DesktopInfoIn: t.typedef = ...
    DesktopInfoOut: t.typedef = ...
    CreateManagedShortLinkResponseIn: t.typedef = ...
    CreateManagedShortLinkResponseOut: t.typedef = ...
    AndroidInfoIn: t.typedef = ...
    AndroidInfoOut: t.typedef = ...
    ITunesConnectAnalyticsIn: t.typedef = ...
    ITunesConnectAnalyticsOut: t.typedef = ...
    GetIosPostInstallAttributionRequestIn: t.typedef = ...
    GetIosPostInstallAttributionRequestOut: t.typedef = ...
    AnalyticsInfoIn: t.typedef = ...
    AnalyticsInfoOut: t.typedef = ...
    GetIosPostInstallAttributionResponseIn: t.typedef = ...
    GetIosPostInstallAttributionResponseOut: t.typedef = ...
    CreateManagedShortLinkRequestIn: t.typedef = ...
    CreateManagedShortLinkRequestOut: t.typedef = ...
    GetIosReopenAttributionResponseIn: t.typedef = ...
    GetIosReopenAttributionResponseOut: t.typedef = ...
    ManagedShortLinkIn: t.typedef = ...
    ManagedShortLinkOut: t.typedef = ...
    DeviceInfoIn: t.typedef = ...
    DeviceInfoOut: t.typedef = ...
    NavigationInfoIn: t.typedef = ...
    NavigationInfoOut: t.typedef = ...
    DynamicLinkInfoIn: t.typedef = ...
    DynamicLinkInfoOut: t.typedef = ...
    DynamicLinkStatsIn: t.typedef = ...
    DynamicLinkStatsOut: t.typedef = ...
    DynamicLinkEventStatIn: t.typedef = ...
    DynamicLinkEventStatOut: t.typedef = ...
    CreateShortDynamicLinkRequestIn: t.typedef = ...
    CreateShortDynamicLinkRequestOut: t.typedef = ...
    GooglePlayAnalyticsIn: t.typedef = ...
    GooglePlayAnalyticsOut: t.typedef = ...
    GetIosReopenAttributionRequestIn: t.typedef = ...
    GetIosReopenAttributionRequestOut: t.typedef = ...

class FuncList:
    v1ReopenAttribution: t.func = ...
    v1InstallAttribution: t.func = ...
    v1GetLinkStats: t.func = ...
    shortLinksCreate: t.func = ...
    managedShortLinksCreate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_firebasedynamiclinks() -> Import: ...
