from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    CloudAuditOptionsIn: t.typedef = ...
    CloudAuditOptionsOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ConditionIn: t.typedef = ...
    ConditionOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    LogConfigIn: t.typedef = ...
    LogConfigOut: t.typedef = ...
    DataAccessOptionsIn: t.typedef = ...
    DataAccessOptionsOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    CounterOptionsIn: t.typedef = ...
    CounterOptionsOut: t.typedef = ...
    RuleIn: t.typedef = ...
    RuleOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    AuthorizationLoggingOptionsIn: t.typedef = ...
    AuthorizationLoggingOptionsOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    CustomFieldIn: t.typedef = ...
    CustomFieldOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsGameServerDeploymentsSetIamPolicy: t.func = ...
    projectsLocationsGameServerDeploymentsGetIamPolicy: t.func = ...
    projectsLocationsGameServerDeploymentsTestIamPermissions: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_gameservices() -> Import: ...
