from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    PlayerIn: t.typedef = ...
    PlayerOut: t.typedef = ...
    AchievementResetMultipleForAllRequestIn: t.typedef = ...
    AchievementResetMultipleForAllRequestOut: t.typedef = ...
    PlayerScoreResetResponseIn: t.typedef = ...
    PlayerScoreResetResponseOut: t.typedef = ...
    ScoresResetMultipleForAllRequestIn: t.typedef = ...
    ScoresResetMultipleForAllRequestOut: t.typedef = ...
    AchievementResetResponseIn: t.typedef = ...
    AchievementResetResponseOut: t.typedef = ...
    EventsResetMultipleForAllRequestIn: t.typedef = ...
    EventsResetMultipleForAllRequestOut: t.typedef = ...
    HiddenPlayerIn: t.typedef = ...
    HiddenPlayerOut: t.typedef = ...
    GamesPlayerLevelResourceIn: t.typedef = ...
    GamesPlayerLevelResourceOut: t.typedef = ...
    PlayerScoreResetAllResponseIn: t.typedef = ...
    PlayerScoreResetAllResponseOut: t.typedef = ...
    HiddenPlayerListIn: t.typedef = ...
    HiddenPlayerListOut: t.typedef = ...
    AchievementResetAllResponseIn: t.typedef = ...
    AchievementResetAllResponseOut: t.typedef = ...
    GamesPlayerExperienceInfoResourceIn: t.typedef = ...
    GamesPlayerExperienceInfoResourceOut: t.typedef = ...
    ProfileSettingsIn: t.typedef = ...
    ProfileSettingsOut: t.typedef = ...

class FuncList:
    playersUnhide: t.func = ...
    playersHide: t.func = ...
    eventsResetForAllPlayers: t.func = ...
    eventsResetAll: t.func = ...
    eventsResetMultipleForAllPlayers: t.func = ...
    eventsReset: t.func = ...
    eventsResetAllForAllPlayers: t.func = ...
    achievementsResetForAllPlayers: t.func = ...
    achievementsResetAll: t.func = ...
    achievementsResetMultipleForAllPlayers: t.func = ...
    achievementsResetAllForAllPlayers: t.func = ...
    achievementsReset: t.func = ...
    applicationsListHidden: t.func = ...
    scoresResetAllForAllPlayers: t.func = ...
    scoresResetMultipleForAllPlayers: t.func = ...
    scoresResetForAllPlayers: t.func = ...
    scoresReset: t.func = ...
    scoresResetAll: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_gamesManagement() -> Import: ...
