from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    TrafficStatsIn: t.typedef = ...
    TrafficStatsOut: t.typedef = ...
    ListTrafficStatsResponseIn: t.typedef = ...
    ListTrafficStatsResponseOut: t.typedef = ...
    ListDomainsResponseIn: t.typedef = ...
    ListDomainsResponseOut: t.typedef = ...
    IpReputationIn: t.typedef = ...
    IpReputationOut: t.typedef = ...
    FeedbackLoopIn: t.typedef = ...
    FeedbackLoopOut: t.typedef = ...
    DeliveryErrorIn: t.typedef = ...
    DeliveryErrorOut: t.typedef = ...
    DomainIn: t.typedef = ...
    DomainOut: t.typedef = ...

class FuncList:
    domainsGet: t.func = ...
    domainsList: t.func = ...
    domainsTrafficStatsList: t.func = ...
    domainsTrafficStatsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_gmailpostmastertools() -> Import: ...
