from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    RequestSyncDevicesResponseIn: t.typedef = ...
    RequestSyncDevicesResponseOut: t.typedef = ...
    SyncRequestIn: t.typedef = ...
    SyncRequestOut: t.typedef = ...
    SyncResponseIn: t.typedef = ...
    SyncResponseOut: t.typedef = ...
    QueryRequestPayloadIn: t.typedef = ...
    QueryRequestPayloadOut: t.typedef = ...
    QueryRequestInputIn: t.typedef = ...
    QueryRequestInputOut: t.typedef = ...
    ReportStateAndNotificationResponseIn: t.typedef = ...
    ReportStateAndNotificationResponseOut: t.typedef = ...
    SyncResponsePayloadIn: t.typedef = ...
    SyncResponsePayloadOut: t.typedef = ...
    QueryRequestIn: t.typedef = ...
    QueryRequestOut: t.typedef = ...
    RequestSyncDevicesRequestIn: t.typedef = ...
    RequestSyncDevicesRequestOut: t.typedef = ...
    ReportStateAndNotificationRequestIn: t.typedef = ...
    ReportStateAndNotificationRequestOut: t.typedef = ...
    DeviceNamesIn: t.typedef = ...
    DeviceNamesOut: t.typedef = ...
    DeviceIn: t.typedef = ...
    DeviceOut: t.typedef = ...
    DeviceInfoIn: t.typedef = ...
    DeviceInfoOut: t.typedef = ...
    ReportStateAndNotificationDeviceIn: t.typedef = ...
    ReportStateAndNotificationDeviceOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    AgentOtherDeviceIdIn: t.typedef = ...
    AgentOtherDeviceIdOut: t.typedef = ...
    QueryResponseIn: t.typedef = ...
    QueryResponseOut: t.typedef = ...
    QueryResponsePayloadIn: t.typedef = ...
    QueryResponsePayloadOut: t.typedef = ...
    AgentDeviceIdIn: t.typedef = ...
    AgentDeviceIdOut: t.typedef = ...
    StateAndNotificationPayloadIn: t.typedef = ...
    StateAndNotificationPayloadOut: t.typedef = ...

class FuncList:
    agentUsersDelete: t.func = ...
    devicesQuery: t.func = ...
    devicesReportStateAndNotification: t.func = ...
    devicesSync: t.func = ...
    devicesRequestSync: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_homegraph() -> Import: ...
