from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleIamV2DenyRuleIn: t.typedef = ...
    GoogleIamV2DenyRuleOut: t.typedef = ...
    GoogleIamAdminV1AuditDataPermissionDeltaIn: t.typedef = ...
    GoogleIamAdminV1AuditDataPermissionDeltaOut: t.typedef = ...
    GoogleIamAdminV1AuditDataIn: t.typedef = ...
    GoogleIamAdminV1AuditDataOut: t.typedef = ...
    GoogleIamV1LoggingAuditDataIn: t.typedef = ...
    GoogleIamV1LoggingAuditDataOut: t.typedef = ...
    GoogleIamV1betaWorkloadIdentityPoolOperationMetadataIn: t.typedef = ...
    GoogleIamV1betaWorkloadIdentityPoolOperationMetadataOut: t.typedef = ...
    GoogleIamV2PolicyRuleIn: t.typedef = ...
    GoogleIamV2PolicyRuleOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleTypeExprIn: t.typedef = ...
    GoogleTypeExprOut: t.typedef = ...
    GoogleIamV1BindingDeltaIn: t.typedef = ...
    GoogleIamV1BindingDeltaOut: t.typedef = ...
    GoogleIamV2PolicyOperationMetadataIn: t.typedef = ...
    GoogleIamV2PolicyOperationMetadataOut: t.typedef = ...
    GoogleIamV2ListPoliciesResponseIn: t.typedef = ...
    GoogleIamV2ListPoliciesResponseOut: t.typedef = ...
    GoogleIamV2PolicyIn: t.typedef = ...
    GoogleIamV2PolicyOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleIamV1PolicyDeltaIn: t.typedef = ...
    GoogleIamV1PolicyDeltaOut: t.typedef = ...

class FuncList:
    policiesGet: t.func = ...
    policiesDelete: t.func = ...
    policiesListPolicies: t.func = ...
    policiesCreatePolicy: t.func = ...
    policiesUpdate: t.func = ...
    policiesOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_iam() -> Import: ...
