from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    PermissionIn: t.typedef = ...
    PermissionOut: t.typedef = ...
    CreatePermissionRequestIn: t.typedef = ...
    CreatePermissionRequestOut: t.typedef = ...
    TextContentIn: t.typedef = ...
    TextContentOut: t.typedef = ...
    BatchCreatePermissionsRequestIn: t.typedef = ...
    BatchCreatePermissionsRequestOut: t.typedef = ...
    ListItemIn: t.typedef = ...
    ListItemOut: t.typedef = ...
    FamilyIn: t.typedef = ...
    FamilyOut: t.typedef = ...
    ListContentIn: t.typedef = ...
    ListContentOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    GroupIn: t.typedef = ...
    GroupOut: t.typedef = ...
    BatchCreatePermissionsResponseIn: t.typedef = ...
    BatchCreatePermissionsResponseOut: t.typedef = ...
    AttachmentIn: t.typedef = ...
    AttachmentOut: t.typedef = ...
    NoteIn: t.typedef = ...
    NoteOut: t.typedef = ...
    ListNotesResponseIn: t.typedef = ...
    ListNotesResponseOut: t.typedef = ...
    BatchDeletePermissionsRequestIn: t.typedef = ...
    BatchDeletePermissionsRequestOut: t.typedef = ...
    UserIn: t.typedef = ...
    UserOut: t.typedef = ...
    SectionIn: t.typedef = ...
    SectionOut: t.typedef = ...

class FuncList:
    notesList: t.func = ...
    notesDelete: t.func = ...
    notesGet: t.func = ...
    notesCreate: t.func = ...
    notesPermissionsBatchCreate: t.func = ...
    notesPermissionsBatchDelete: t.func = ...
    mediaDownload: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_keep() -> Import: ...
