from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudKmsInventoryV1SearchProtectedResourcesResponseIn: t.typedef = ...
    GoogleCloudKmsInventoryV1SearchProtectedResourcesResponseOut: t.typedef = ...
    GoogleCloudKmsInventoryV1ListCryptoKeysResponseIn: t.typedef = ...
    GoogleCloudKmsInventoryV1ListCryptoKeysResponseOut: t.typedef = ...
    GoogleCloudKmsV1CryptoKeyVersionIn: t.typedef = ...
    GoogleCloudKmsV1CryptoKeyVersionOut: t.typedef = ...
    GoogleCloudKmsV1ExternalProtectionLevelOptionsIn: t.typedef = ...
    GoogleCloudKmsV1ExternalProtectionLevelOptionsOut: t.typedef = ...
    GoogleCloudKmsV1KeyOperationAttestationIn: t.typedef = ...
    GoogleCloudKmsV1KeyOperationAttestationOut: t.typedef = ...
    GoogleCloudKmsV1CryptoKeyIn: t.typedef = ...
    GoogleCloudKmsV1CryptoKeyOut: t.typedef = ...
    GoogleCloudKmsInventoryV1ProtectedResourcesSummaryIn: t.typedef = ...
    GoogleCloudKmsInventoryV1ProtectedResourcesSummaryOut: t.typedef = ...
    GoogleCloudKmsV1KeyOperationAttestationCertificateChainsIn: t.typedef = ...
    GoogleCloudKmsV1KeyOperationAttestationCertificateChainsOut: t.typedef = ...
    GoogleCloudKmsInventoryV1ProtectedResourceIn: t.typedef = ...
    GoogleCloudKmsInventoryV1ProtectedResourceOut: t.typedef = ...
    GoogleCloudKmsV1CryptoKeyVersionTemplateIn: t.typedef = ...
    GoogleCloudKmsV1CryptoKeyVersionTemplateOut: t.typedef = ...

class FuncList:
    organizationsProtectedResourcesSearch: t.func = ...
    projectsCryptoKeysList: t.func = ...
    projectsLocationsKeyRingsCryptoKeysGetProtectedResourcesSummary: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_kmsinventory() -> Import: ...
