from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleExampleLibraryagentV1ListBooksResponseIn: t.typedef = ...
    GoogleExampleLibraryagentV1ListBooksResponseOut: t.typedef = ...
    GoogleExampleLibraryagentV1ShelfIn: t.typedef = ...
    GoogleExampleLibraryagentV1ShelfOut: t.typedef = ...
    GoogleExampleLibraryagentV1ListShelvesResponseIn: t.typedef = ...
    GoogleExampleLibraryagentV1ListShelvesResponseOut: t.typedef = ...
    GoogleExampleLibraryagentV1BookIn: t.typedef = ...
    GoogleExampleLibraryagentV1BookOut: t.typedef = ...

class FuncList:
    shelvesList: t.func = ...
    shelvesGet: t.func = ...
    shelvesBooksList: t.func = ...
    shelvesBooksReturn: t.func = ...
    shelvesBooksBorrow: t.func = ...
    shelvesBooksGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_libraryagent() -> Import: ...
