from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    LicenseAssignmentListIn: t.typedef = ...
    LicenseAssignmentListOut: t.typedef = ...
    LicenseAssignmentIn: t.typedef = ...
    LicenseAssignmentOut: t.typedef = ...
    LicenseAssignmentInsertIn: t.typedef = ...
    LicenseAssignmentInsertOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...

class FuncList:
    licenseAssignmentsDelete: t.func = ...
    licenseAssignmentsGet: t.func = ...
    licenseAssignmentsInsert: t.func = ...
    licenseAssignmentsUpdate: t.func = ...
    licenseAssignmentsListForProduct: t.func = ...
    licenseAssignmentsPatch: t.func = ...
    licenseAssignmentsListForProductAndSku: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_licensing() -> Import: ...
