from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ImageIn: t.typedef = ...
    ImageOut: t.typedef = ...
    ProductCertificationIn: t.typedef = ...
    ProductCertificationOut: t.typedef = ...
    CertificationIn: t.typedef = ...
    CertificationOut: t.typedef = ...
    IssueIn: t.typedef = ...
    IssueOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ProductIn: t.typedef = ...
    ProductOut: t.typedef = ...
    FeatureDescriptionIn: t.typedef = ...
    FeatureDescriptionOut: t.typedef = ...
    CapacityIn: t.typedef = ...
    CapacityOut: t.typedef = ...
    ProductDetailIn: t.typedef = ...
    ProductDetailOut: t.typedef = ...
    NutritionIn: t.typedef = ...
    NutritionOut: t.typedef = ...
    VoluntaryNutritionFactIn: t.typedef = ...
    VoluntaryNutritionFactOut: t.typedef = ...
    ListProductCertificationsResponseIn: t.typedef = ...
    ListProductCertificationsResponseOut: t.typedef = ...
    ListProductsResponseIn: t.typedef = ...
    ListProductsResponseOut: t.typedef = ...
    AttributesIn: t.typedef = ...
    AttributesOut: t.typedef = ...
    GroceryIn: t.typedef = ...
    GroceryOut: t.typedef = ...
    DestinationStatusIn: t.typedef = ...
    DestinationStatusOut: t.typedef = ...
    FloatUnitIn: t.typedef = ...
    FloatUnitOut: t.typedef = ...
    CountIn: t.typedef = ...
    CountOut: t.typedef = ...
    PriceIn: t.typedef = ...
    PriceOut: t.typedef = ...

class FuncList:
    accountsLanguagesProductCertificationsList: t.func = ...
    accountsLanguagesProductCertificationsPatch: t.func = ...
    accountsLanguagesProductCertificationsGet: t.func = ...
    accountsLanguagesProductCertificationsDelete: t.func = ...
    accountsProductsList: t.func = ...
    accountsProductsUpdate: t.func = ...
    accountsProductsDelete: t.func = ...
    accountsProductsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_manufacturers() -> Import: ...
