from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleCloudMlV1__ParameterSpecIn: t.typedef = ...
    GoogleCloudMlV1__ParameterSpecOut: t.typedef = ...
    GoogleCloudMlV1__MeasurementIn: t.typedef = ...
    GoogleCloudMlV1__MeasurementOut: t.typedef = ...
    GoogleLongrunning__OperationIn: t.typedef = ...
    GoogleLongrunning__OperationOut: t.typedef = ...
    GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetricIn: t.typedef = ...
    GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetricOut: t.typedef = ...
    GoogleCloudMlV1_Trial_ParameterIn: t.typedef = ...
    GoogleCloudMlV1_Trial_ParameterOut: t.typedef = ...
    GoogleCloudMlV1__VersionIn: t.typedef = ...
    GoogleCloudMlV1__VersionOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_ParameterSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_ParameterSpecOut: t.typedef = ...
    GoogleCloudMlV1__RequestLoggingConfigIn: t.typedef = ...
    GoogleCloudMlV1__RequestLoggingConfigOut: t.typedef = ...
    GoogleCloudMlV1__TrialIn: t.typedef = ...
    GoogleCloudMlV1__TrialOut: t.typedef = ...
    GoogleCloudMlV1__ExplainRequestIn: t.typedef = ...
    GoogleCloudMlV1__ExplainRequestOut: t.typedef = ...
    GoogleCloudMlV1__EncryptionConfigIn: t.typedef = ...
    GoogleCloudMlV1__EncryptionConfigOut: t.typedef = ...
    GoogleCloudMlV1__SuggestTrialsResponseIn: t.typedef = ...
    GoogleCloudMlV1__SuggestTrialsResponseOut: t.typedef = ...
    GoogleCloudMlV1__PredictionInputIn: t.typedef = ...
    GoogleCloudMlV1__PredictionInputOut: t.typedef = ...
    GoogleCloudMlV1__ExplanationConfigIn: t.typedef = ...
    GoogleCloudMlV1__ExplanationConfigOut: t.typedef = ...
    GoogleCloudMlV1__IntegratedGradientsAttributionIn: t.typedef = ...
    GoogleCloudMlV1__IntegratedGradientsAttributionOut: t.typedef = ...
    GoogleCloudMlV1__ReplicaConfigIn: t.typedef = ...
    GoogleCloudMlV1__ReplicaConfigOut: t.typedef = ...
    GoogleCloudMlV1__ListJobsResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListJobsResponseOut: t.typedef = ...
    GoogleCloudMlV1__ListVersionsResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListVersionsResponseOut: t.typedef = ...
    GoogleCloudMlV1__ManualScalingIn: t.typedef = ...
    GoogleCloudMlV1__ManualScalingOut: t.typedef = ...
    GoogleIamV1__TestIamPermissionsRequestIn: t.typedef = ...
    GoogleIamV1__TestIamPermissionsRequestOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpecOut: t.typedef = ...
    GoogleCloudMlV1__JobIn: t.typedef = ...
    GoogleCloudMlV1__JobOut: t.typedef = ...
    GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfigIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfigOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpecIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpecOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1__CheckTrialEarlyStoppingStateMetatdataIn: t.typedef = ...
    GoogleCloudMlV1__CheckTrialEarlyStoppingStateMetatdataOut: t.typedef = ...
    GoogleCloudMlV1__BuiltInAlgorithmOutputIn: t.typedef = ...
    GoogleCloudMlV1__BuiltInAlgorithmOutputOut: t.typedef = ...
    GoogleCloudMlV1__HyperparameterSpecIn: t.typedef = ...
    GoogleCloudMlV1__HyperparameterSpecOut: t.typedef = ...
    GoogleCloudMlV1__PredictionOutputIn: t.typedef = ...
    GoogleCloudMlV1__PredictionOutputOut: t.typedef = ...
    GoogleCloudMlV1__ConfigIn: t.typedef = ...
    GoogleCloudMlV1__ConfigOut: t.typedef = ...
    GoogleType__ExprIn: t.typedef = ...
    GoogleType__ExprOut: t.typedef = ...
    GoogleLongrunning__ListOperationsResponseIn: t.typedef = ...
    GoogleLongrunning__ListOperationsResponseOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpecIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpecOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpecOut: t.typedef = ...
    GoogleIamV1__AuditConfigIn: t.typedef = ...
    GoogleIamV1__AuditConfigOut: t.typedef = ...
    GoogleCloudMlV1__ListLocationsResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListLocationsResponseOut: t.typedef = ...
    GoogleCloudMlV1__CapabilityIn: t.typedef = ...
    GoogleCloudMlV1__CapabilityOut: t.typedef = ...
    GoogleCloudMlV1__ListOptimalTrialsResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListOptimalTrialsResponseOut: t.typedef = ...
    GoogleCloudMlV1__TrainingOutputIn: t.typedef = ...
    GoogleCloudMlV1__TrainingOutputOut: t.typedef = ...
    GoogleCloudMlV1__SuggestTrialsRequestIn: t.typedef = ...
    GoogleCloudMlV1__SuggestTrialsRequestOut: t.typedef = ...
    GoogleCloudMlV1__AcceleratorConfigIn: t.typedef = ...
    GoogleCloudMlV1__AcceleratorConfigOut: t.typedef = ...
    GoogleCloudMlV1__AutomatedStoppingConfigIn: t.typedef = ...
    GoogleCloudMlV1__AutomatedStoppingConfigOut: t.typedef = ...
    GoogleApi__HttpBodyIn: t.typedef = ...
    GoogleApi__HttpBodyOut: t.typedef = ...
    GoogleCloudMlV1_Measurement_MetricIn: t.typedef = ...
    GoogleCloudMlV1_Measurement_MetricOut: t.typedef = ...
    GoogleCloudMlV1__HyperparameterOutputIn: t.typedef = ...
    GoogleCloudMlV1__HyperparameterOutputOut: t.typedef = ...
    GoogleCloudMlV1__MetricSpecIn: t.typedef = ...
    GoogleCloudMlV1__MetricSpecOut: t.typedef = ...
    GoogleCloudMlV1__SchedulingIn: t.typedef = ...
    GoogleCloudMlV1__SchedulingOut: t.typedef = ...
    GoogleCloudMlV1__ListStudiesResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListStudiesResponseOut: t.typedef = ...
    GoogleCloudMlV1__ContainerPortIn: t.typedef = ...
    GoogleCloudMlV1__ContainerPortOut: t.typedef = ...
    GoogleCloudMlV1__TrainingInputIn: t.typedef = ...
    GoogleCloudMlV1__TrainingInputOut: t.typedef = ...
    GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequestIn: t.typedef = ...
    GoogleCloudMlV1__CheckTrialEarlyStoppingStateRequestOut: t.typedef = ...
    GoogleCloudMlV1__StopTrialRequestIn: t.typedef = ...
    GoogleCloudMlV1__StopTrialRequestOut: t.typedef = ...
    GoogleIamV1__TestIamPermissionsResponseIn: t.typedef = ...
    GoogleIamV1__TestIamPermissionsResponseOut: t.typedef = ...
    GoogleCloudMlV1__ListTrialsResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListTrialsResponseOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpecOut: t.typedef = ...
    GoogleCloudMlV1__AddTrialMeasurementRequestIn: t.typedef = ...
    GoogleCloudMlV1__AddTrialMeasurementRequestOut: t.typedef = ...
    GoogleIamV1__AuditLogConfigIn: t.typedef = ...
    GoogleIamV1__AuditLogConfigOut: t.typedef = ...
    GoogleCloudMlV1__SetDefaultVersionRequestIn: t.typedef = ...
    GoogleCloudMlV1__SetDefaultVersionRequestOut: t.typedef = ...
    GoogleCloudMlV1__ListModelsResponseIn: t.typedef = ...
    GoogleCloudMlV1__ListModelsResponseOut: t.typedef = ...
    GoogleCloudMlV1__StudyIn: t.typedef = ...
    GoogleCloudMlV1__StudyOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpecOut: t.typedef = ...
    GoogleCloudMlV1__XraiAttributionIn: t.typedef = ...
    GoogleCloudMlV1__XraiAttributionOut: t.typedef = ...
    GoogleIamV1__BindingIn: t.typedef = ...
    GoogleIamV1__BindingOut: t.typedef = ...
    GoogleCloudMlV1__CancelJobRequestIn: t.typedef = ...
    GoogleCloudMlV1__CancelJobRequestOut: t.typedef = ...
    GoogleCloudMlV1__GetConfigResponseIn: t.typedef = ...
    GoogleCloudMlV1__GetConfigResponseOut: t.typedef = ...
    GoogleCloudMlV1__ContainerSpecIn: t.typedef = ...
    GoogleCloudMlV1__ContainerSpecOut: t.typedef = ...
    GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfigIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfigOut: t.typedef = (
        ...
    )
    GoogleIamV1__SetIamPolicyRequestIn: t.typedef = ...
    GoogleIamV1__SetIamPolicyRequestOut: t.typedef = ...
    GoogleCloudMlV1__RouteMapIn: t.typedef = ...
    GoogleCloudMlV1__RouteMapOut: t.typedef = ...
    GoogleCloudMlV1__ListOptimalTrialsRequestIn: t.typedef = ...
    GoogleCloudMlV1__ListOptimalTrialsRequestOut: t.typedef = ...
    GoogleCloudMlV1__AutoScalingIn: t.typedef = ...
    GoogleCloudMlV1__AutoScalingOut: t.typedef = ...
    GoogleCloudMlV1__SuggestTrialsMetadataIn: t.typedef = ...
    GoogleCloudMlV1__SuggestTrialsMetadataOut: t.typedef = ...
    GoogleCloudMlV1__OperationMetadataIn: t.typedef = ...
    GoogleCloudMlV1__OperationMetadataOut: t.typedef = ...
    GoogleCloudMlV1__ModelIn: t.typedef = ...
    GoogleCloudMlV1__ModelOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_MetricSpecIn: t.typedef = ...
    GoogleCloudMlV1_StudyConfig_MetricSpecOut: t.typedef = ...
    GoogleIamV1__PolicyIn: t.typedef = ...
    GoogleIamV1__PolicyOut: t.typedef = ...
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpecIn: t.typedef = (
        ...
    )
    GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpecOut: t.typedef = (
        ...
    )
    GoogleCloudMlV1__LocationIn: t.typedef = ...
    GoogleCloudMlV1__LocationOut: t.typedef = ...
    GoogleRpc__StatusIn: t.typedef = ...
    GoogleRpc__StatusOut: t.typedef = ...
    GoogleProtobuf__EmptyIn: t.typedef = ...
    GoogleProtobuf__EmptyOut: t.typedef = ...
    GoogleCloudMlV1__StudyConfigIn: t.typedef = ...
    GoogleCloudMlV1__StudyConfigOut: t.typedef = ...
    GoogleCloudMlV1__EnvVarIn: t.typedef = ...
    GoogleCloudMlV1__EnvVarOut: t.typedef = ...
    GoogleCloudMlV1__SampledShapleyAttributionIn: t.typedef = ...
    GoogleCloudMlV1__SampledShapleyAttributionOut: t.typedef = ...
    GoogleCloudMlV1__PredictRequestIn: t.typedef = ...
    GoogleCloudMlV1__PredictRequestOut: t.typedef = ...
    GoogleCloudMlV1__CompleteTrialRequestIn: t.typedef = ...
    GoogleCloudMlV1__CompleteTrialRequestOut: t.typedef = ...
    GoogleCloudMlV1__CheckTrialEarlyStoppingStateResponseIn: t.typedef = ...
    GoogleCloudMlV1__CheckTrialEarlyStoppingStateResponseOut: t.typedef = ...
    GoogleCloudMlV1__DiskConfigIn: t.typedef = ...
    GoogleCloudMlV1__DiskConfigOut: t.typedef = ...

class FuncList:
    projectsExplain: t.func = ...
    projectsPredict: t.func = ...
    projectsGetConfig: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsStudiesCreate: t.func = ...
    projectsLocationsStudiesGet: t.func = ...
    projectsLocationsStudiesList: t.func = ...
    projectsLocationsStudiesDelete: t.func = ...
    projectsLocationsStudiesTrialsStop: t.func = ...
    projectsLocationsStudiesTrialsList: t.func = ...
    projectsLocationsStudiesTrialsGet: t.func = ...
    projectsLocationsStudiesTrialsCreate: t.func = ...
    projectsLocationsStudiesTrialsDelete: t.func = ...
    projectsLocationsStudiesTrialsAddMeasurement: t.func = ...
    projectsLocationsStudiesTrialsListOptimalTrials: t.func = ...
    projectsLocationsStudiesTrialsCheckEarlyStoppingState: t.func = ...
    projectsLocationsStudiesTrialsComplete: t.func = ...
    projectsLocationsStudiesTrialsSuggest: t.func = ...
    projectsJobsPatch: t.func = ...
    projectsJobsSetIamPolicy: t.func = ...
    projectsJobsCreate: t.func = ...
    projectsJobsCancel: t.func = ...
    projectsJobsList: t.func = ...
    projectsJobsTestIamPermissions: t.func = ...
    projectsJobsGetIamPolicy: t.func = ...
    projectsJobsGet: t.func = ...
    projectsOperationsList: t.func = ...
    projectsOperationsGet: t.func = ...
    projectsOperationsCancel: t.func = ...
    projectsModelsPatch: t.func = ...
    projectsModelsList: t.func = ...
    projectsModelsGetIamPolicy: t.func = ...
    projectsModelsSetIamPolicy: t.func = ...
    projectsModelsCreate: t.func = ...
    projectsModelsDelete: t.func = ...
    projectsModelsTestIamPermissions: t.func = ...
    projectsModelsGet: t.func = ...
    projectsModelsVersionsGet: t.func = ...
    projectsModelsVersionsDelete: t.func = ...
    projectsModelsVersionsList: t.func = ...
    projectsModelsVersionsPatch: t.func = ...
    projectsModelsVersionsCreate: t.func = ...
    projectsModelsVersionsSetDefault: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_ml() -> Import: ...
