from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1TimelineSpecIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1TimelineSpecOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SlowRenderingRateMetricSetIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SlowRenderingRateMetricSetOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetResponseIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetResponseOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AppIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AppOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetRequestIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetRequestOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1ExcessiveWakeupRateMetricSetIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ExcessiveWakeupRateMetricSetOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryErrorCountMetricSetResponseIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryErrorCountMetricSetResponseOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetRequestIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetRequestOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1DecimalConfidenceIntervalIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DecimalConfidenceIntervalOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetRequestIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetRequestOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetResponseIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetResponseOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1ErrorReportIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ErrorReportOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SearchAccessibleAppsResponseIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SearchAccessibleAppsResponseOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SearchErrorIssuesResponseIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SearchErrorIssuesResponseOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SearchErrorReportsResponseIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SearchErrorReportsResponseOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ReleaseFilterOptionsIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ReleaseFilterOptionsOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshnessIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshnessOut: t.typedef = ...
    GoogleTypeDecimalIn: t.typedef = ...
    GoogleTypeDecimalOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1StuckBackgroundWakelockRateMetricSetIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1StuckBackgroundWakelockRateMetricSetOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1MetricValueIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1MetricValueOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1MetricsRowIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1MetricsRowOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1OsVersionIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1OsVersionOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1TrackIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1TrackOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AnrRateMetricSetIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AnrRateMetricSetOut: t.typedef = ...
    GoogleTypeDateTimeIn: t.typedef = ...
    GoogleTypeDateTimeOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ReleaseIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ReleaseOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetResponseIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetResponseOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1AppVersionIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AppVersionOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SlowStartRateMetricSetIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1SlowStartRateMetricSetOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AnomalyIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1AnomalyOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetResponseIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetResponseOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1ErrorIssueIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ErrorIssueOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DimensionValueIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DimensionValueOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetResponseIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetResponseOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetRequestIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetRequestOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetRequestIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetRequestOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetResponseIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetResponseOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1ListAnomaliesResponseIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ListAnomaliesResponseOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryErrorCountMetricSetRequestIn: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryErrorCountMetricSetRequestOut: t.typedef = (
        ...
    )
    GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetRequestIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetRequestOut: t.typedef = (
        ...
    )
    GoogleTypeTimeZoneIn: t.typedef = ...
    GoogleTypeTimeZoneOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DeviceModelSummaryIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DeviceModelSummaryOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1CrashRateMetricSetIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1CrashRateMetricSetOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1FreshnessInfoIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1FreshnessInfoOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DeviceIdIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1DeviceIdOut: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ErrorCountMetricSetIn: t.typedef = ...
    GooglePlayDeveloperReportingV1beta1ErrorCountMetricSetOut: t.typedef = ...

class FuncList:
    anomaliesList: t.func = ...
    appsSearch: t.func = ...
    appsFetchReleaseFilterOptions: t.func = ...
    vitalsSlowrenderingrateGet: t.func = ...
    vitalsSlowrenderingrateQuery: t.func = ...
    vitalsSlowstartrateQuery: t.func = ...
    vitalsSlowstartrateGet: t.func = ...
    vitalsErrorsIssuesSearch: t.func = ...
    vitalsErrorsReportsSearch: t.func = ...
    vitalsErrorsCountsGet: t.func = ...
    vitalsErrorsCountsQuery: t.func = ...
    vitalsCrashrateGet: t.func = ...
    vitalsCrashrateQuery: t.func = ...
    vitalsStuckbackgroundwakelockrateGet: t.func = ...
    vitalsStuckbackgroundwakelockrateQuery: t.func = ...
    vitalsAnrrateGet: t.func = ...
    vitalsAnrrateQuery: t.func = ...
    vitalsExcessivewakeuprateQuery: t.func = ...
    vitalsExcessivewakeuprateGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_playdeveloperreporting() -> Import: ...
