from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleIamV1BindingIn: t.typedef = ...
    GoogleIamV1BindingOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayResultIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayResultOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1BindingExplanationIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1BindingExplanationOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ListReplayResultsResponseIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ListReplayResultsResponseOut: t.typedef = ...
    GoogleIamV1PolicyIn: t.typedef = ...
    GoogleIamV1PolicyOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1AccessTupleIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1AccessTupleOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayOperationMetadataIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayOperationMetadataOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayResultsSummaryIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayResultsSummaryOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ExplainedPolicyIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ExplainedPolicyOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipOut: t.typedef = (
        ...
    )
    GoogleCloudPolicysimulatorV1AccessStateDiffIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1AccessStateDiffOut: t.typedef = ...
    GoogleLongrunningListOperationsResponseIn: t.typedef = ...
    GoogleLongrunningListOperationsResponseOut: t.typedef = ...
    GoogleIamV1AuditConfigIn: t.typedef = ...
    GoogleIamV1AuditConfigOut: t.typedef = ...
    GoogleIamV1AuditLogConfigIn: t.typedef = ...
    GoogleIamV1AuditLogConfigOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayDiffIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayDiffOut: t.typedef = ...
    GoogleTypeDateIn: t.typedef = ...
    GoogleTypeDateOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ExplainedAccessIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ExplainedAccessOut: t.typedef = ...
    GoogleLongrunningOperationIn: t.typedef = ...
    GoogleLongrunningOperationOut: t.typedef = ...
    GoogleRpcStatusIn: t.typedef = ...
    GoogleRpcStatusOut: t.typedef = ...
    GoogleTypeExprIn: t.typedef = ...
    GoogleTypeExprOut: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayConfigIn: t.typedef = ...
    GoogleCloudPolicysimulatorV1ReplayConfigOut: t.typedef = ...

class FuncList:
    operationsGet: t.func = ...
    operationsList: t.func = ...
    foldersLocationsReplaysCreate: t.func = ...
    foldersLocationsReplaysGet: t.func = ...
    foldersLocationsReplaysOperationsGet: t.func = ...
    foldersLocationsReplaysOperationsList: t.func = ...
    foldersLocationsReplaysResultsList: t.func = ...
    organizationsLocationsReplaysCreate: t.func = ...
    organizationsLocationsReplaysGet: t.func = ...
    organizationsLocationsReplaysResultsList: t.func = ...
    organizationsLocationsReplaysOperationsList: t.func = ...
    organizationsLocationsReplaysOperationsGet: t.func = ...
    projectsLocationsReplaysGet: t.func = ...
    projectsLocationsReplaysCreate: t.func = ...
    projectsLocationsReplaysResultsList: t.func = ...
    projectsLocationsReplaysOperationsGet: t.func = ...
    projectsLocationsReplaysOperationsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_policysimulator() -> Import: ...
