from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    ListCertificateRevocationListsResponseIn: t.typedef = ...
    ListCertificateRevocationListsResponseOut: t.typedef = ...
    SubjectConfigIn: t.typedef = ...
    SubjectConfigOut: t.typedef = ...
    X509ExtensionIn: t.typedef = ...
    X509ExtensionOut: t.typedef = ...
    RevokeCertificateRequestIn: t.typedef = ...
    RevokeCertificateRequestOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    EnableCertificateAuthorityRequestIn: t.typedef = ...
    EnableCertificateAuthorityRequestOut: t.typedef = ...
    SubjectAltNamesIn: t.typedef = ...
    SubjectAltNamesOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    SubordinateConfigChainIn: t.typedef = ...
    SubordinateConfigChainOut: t.typedef = ...
    RevokedCertificateIn: t.typedef = ...
    RevokedCertificateOut: t.typedef = ...
    SubjectDescriptionIn: t.typedef = ...
    SubjectDescriptionOut: t.typedef = ...
    X509ParametersIn: t.typedef = ...
    X509ParametersOut: t.typedef = ...
    FetchCaCertsRequestIn: t.typedef = ...
    FetchCaCertsRequestOut: t.typedef = ...
    AccessUrlsIn: t.typedef = ...
    AccessUrlsOut: t.typedef = ...
    ExtendedKeyUsageOptionsIn: t.typedef = ...
    ExtendedKeyUsageOptionsOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    CertChainIn: t.typedef = ...
    CertChainOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    CertificateIn: t.typedef = ...
    CertificateOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    RevocationDetailsIn: t.typedef = ...
    RevocationDetailsOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    PublicKeyIn: t.typedef = ...
    PublicKeyOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    ListCertificatesResponseIn: t.typedef = ...
    ListCertificatesResponseOut: t.typedef = ...
    EcKeyTypeIn: t.typedef = ...
    EcKeyTypeOut: t.typedef = ...
    NameConstraintsIn: t.typedef = ...
    NameConstraintsOut: t.typedef = ...
    KeyUsageOptionsIn: t.typedef = ...
    KeyUsageOptionsOut: t.typedef = ...
    CertificateIdentityConstraintsIn: t.typedef = ...
    CertificateIdentityConstraintsOut: t.typedef = ...
    CertificateConfigIn: t.typedef = ...
    CertificateConfigOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    CertificateDescriptionIn: t.typedef = ...
    CertificateDescriptionOut: t.typedef = ...
    ListCertificateAuthoritiesResponseIn: t.typedef = ...
    ListCertificateAuthoritiesResponseOut: t.typedef = ...
    IssuancePolicyIn: t.typedef = ...
    IssuancePolicyOut: t.typedef = ...
    KeyIdIn: t.typedef = ...
    KeyIdOut: t.typedef = ...
    FetchCaCertsResponseIn: t.typedef = ...
    FetchCaCertsResponseOut: t.typedef = ...
    SubjectIn: t.typedef = ...
    SubjectOut: t.typedef = ...
    ActivateCertificateAuthorityRequestIn: t.typedef = ...
    ActivateCertificateAuthorityRequestOut: t.typedef = ...
    CertificateFingerprintIn: t.typedef = ...
    CertificateFingerprintOut: t.typedef = ...
    ListCaPoolsResponseIn: t.typedef = ...
    ListCaPoolsResponseOut: t.typedef = ...
    IssuanceModesIn: t.typedef = ...
    IssuanceModesOut: t.typedef = ...
    CertificateRevocationListIn: t.typedef = ...
    CertificateRevocationListOut: t.typedef = ...
    SubordinateConfigIn: t.typedef = ...
    SubordinateConfigOut: t.typedef = ...
    CertificateTemplateIn: t.typedef = ...
    CertificateTemplateOut: t.typedef = ...
    ObjectIdIn: t.typedef = ...
    ObjectIdOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    UndeleteCertificateAuthorityRequestIn: t.typedef = ...
    UndeleteCertificateAuthorityRequestOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    CaOptionsIn: t.typedef = ...
    CaOptionsOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    ListCertificateTemplatesResponseIn: t.typedef = ...
    ListCertificateTemplatesResponseOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...
    CaPoolIn: t.typedef = ...
    CaPoolOut: t.typedef = ...
    RsaKeyTypeIn: t.typedef = ...
    RsaKeyTypeOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ReconciliationOperationMetadataIn: t.typedef = ...
    ReconciliationOperationMetadataOut: t.typedef = ...
    KeyVersionSpecIn: t.typedef = ...
    KeyVersionSpecOut: t.typedef = ...
    PublishingOptionsIn: t.typedef = ...
    PublishingOptionsOut: t.typedef = ...
    CertificateAuthorityIn: t.typedef = ...
    CertificateAuthorityOut: t.typedef = ...
    CertificateExtensionConstraintsIn: t.typedef = ...
    CertificateExtensionConstraintsOut: t.typedef = ...
    FetchCertificateAuthorityCsrResponseIn: t.typedef = ...
    FetchCertificateAuthorityCsrResponseOut: t.typedef = ...
    AllowedKeyTypeIn: t.typedef = ...
    AllowedKeyTypeOut: t.typedef = ...
    DisableCertificateAuthorityRequestIn: t.typedef = ...
    DisableCertificateAuthorityRequestOut: t.typedef = ...
    KeyUsageIn: t.typedef = ...
    KeyUsageOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...

class FuncList:
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsCertificateTemplatesCreate: t.func = ...
    projectsLocationsCertificateTemplatesList: t.func = ...
    projectsLocationsCertificateTemplatesDelete: t.func = ...
    projectsLocationsCertificateTemplatesTestIamPermissions: t.func = ...
    projectsLocationsCertificateTemplatesGetIamPolicy: t.func = ...
    projectsLocationsCertificateTemplatesSetIamPolicy: t.func = ...
    projectsLocationsCertificateTemplatesGet: t.func = ...
    projectsLocationsCertificateTemplatesPatch: t.func = ...
    projectsLocationsOperationsGet: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsCaPoolsGet: t.func = ...
    projectsLocationsCaPoolsDelete: t.func = ...
    projectsLocationsCaPoolsSetIamPolicy: t.func = ...
    projectsLocationsCaPoolsTestIamPermissions: t.func = ...
    projectsLocationsCaPoolsList: t.func = ...
    projectsLocationsCaPoolsPatch: t.func = ...
    projectsLocationsCaPoolsGetIamPolicy: t.func = ...
    projectsLocationsCaPoolsFetchCaCerts: t.func = ...
    projectsLocationsCaPoolsCreate: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesDelete: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesList: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesActivate: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesEnable: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesCreate: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesPatch: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesFetch: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesDisable: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesGet: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesUndelete: t.func = ...
    projectsLocationsCaPoolsCertificateAuthoritiesCertificateRevocationListsSetIamPolicy: t.func = (
        ...
    )
    projectsLocationsCaPoolsCertificateAuthoritiesCertificateRevocationListsTestIamPermissions: t.func = (
        ...
    )
    projectsLocationsCaPoolsCertificateAuthoritiesCertificateRevocationListsGetIamPolicy: t.func = (
        ...
    )
    projectsLocationsCaPoolsCertificateAuthoritiesCertificateRevocationListsList: t.func = (
        ...
    )
    projectsLocationsCaPoolsCertificateAuthoritiesCertificateRevocationListsPatch: t.func = (
        ...
    )
    projectsLocationsCaPoolsCertificateAuthoritiesCertificateRevocationListsGet: t.func = (
        ...
    )
    projectsLocationsCaPoolsCertificatesCreate: t.func = ...
    projectsLocationsCaPoolsCertificatesPatch: t.func = ...
    projectsLocationsCaPoolsCertificatesGet: t.func = ...
    projectsLocationsCaPoolsCertificatesList: t.func = ...
    projectsLocationsCaPoolsCertificatesRevoke: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_privateca() -> Import: ...
