from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ReaderIn: t.typedef = ...
    ReaderOut: t.typedef = ...
    EntitlementIn: t.typedef = ...
    EntitlementOut: t.typedef = ...
    DeleteReaderResponseIn: t.typedef = ...
    DeleteReaderResponseOut: t.typedef = ...
    ReaderEntitlementsIn: t.typedef = ...
    ReaderEntitlementsOut: t.typedef = ...

class FuncList:
    publicationsReadersGet: t.func = ...
    publicationsReadersUpdateEntitlements: t.func = ...
    publicationsReadersDelete: t.func = ...
    publicationsReadersGetEntitlements: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_readerrevenuesubscriptionlinking() -> Import: ...
