from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    NodeInfoIn: t.typedef = ...
    NodeInfoOut: t.typedef = ...
    TimeOfDayIn: t.typedef = ...
    TimeOfDayOut: t.typedef = ...
    GoogleCloudRedisV1LocationMetadataIn: t.typedef = ...
    GoogleCloudRedisV1LocationMetadataOut: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    FailoverInstanceRequestIn: t.typedef = ...
    FailoverInstanceRequestOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    GoogleCloudRedisV1ZoneMetadataIn: t.typedef = ...
    GoogleCloudRedisV1ZoneMetadataOut: t.typedef = ...
    InputConfigIn: t.typedef = ...
    InputConfigOut: t.typedef = ...
    GoogleCloudRedisV1OperationMetadataIn: t.typedef = ...
    GoogleCloudRedisV1OperationMetadataOut: t.typedef = ...
    InstanceIn: t.typedef = ...
    InstanceOut: t.typedef = ...
    ImportInstanceRequestIn: t.typedef = ...
    ImportInstanceRequestOut: t.typedef = ...
    RescheduleMaintenanceRequestIn: t.typedef = ...
    RescheduleMaintenanceRequestOut: t.typedef = ...
    TlsCertificateIn: t.typedef = ...
    TlsCertificateOut: t.typedef = ...
    OutputConfigIn: t.typedef = ...
    OutputConfigOut: t.typedef = ...
    ReconciliationOperationMetadataIn: t.typedef = ...
    ReconciliationOperationMetadataOut: t.typedef = ...
    UpgradeInstanceRequestIn: t.typedef = ...
    UpgradeInstanceRequestOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    ListInstancesResponseIn: t.typedef = ...
    ListInstancesResponseOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    InstanceAuthStringIn: t.typedef = ...
    InstanceAuthStringOut: t.typedef = ...
    ExportInstanceRequestIn: t.typedef = ...
    ExportInstanceRequestOut: t.typedef = ...
    GcsDestinationIn: t.typedef = ...
    GcsDestinationOut: t.typedef = ...
    GcsSourceIn: t.typedef = ...
    GcsSourceOut: t.typedef = ...
    MaintenanceScheduleIn: t.typedef = ...
    MaintenanceScheduleOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    PersistenceConfigIn: t.typedef = ...
    PersistenceConfigOut: t.typedef = ...
    MaintenancePolicyIn: t.typedef = ...
    MaintenancePolicyOut: t.typedef = ...
    WeeklyMaintenanceWindowIn: t.typedef = ...
    WeeklyMaintenanceWindowOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...

class FuncList:
    projectsLocationsGet: t.func = ...
    projectsLocationsList: t.func = ...
    projectsLocationsInstancesGet: t.func = ...
    projectsLocationsInstancesFailover: t.func = ...
    projectsLocationsInstancesGetAuthString: t.func = ...
    projectsLocationsInstancesRescheduleMaintenance: t.func = ...
    projectsLocationsInstancesDelete: t.func = ...
    projectsLocationsInstancesPatch: t.func = ...
    projectsLocationsInstancesUpgrade: t.func = ...
    projectsLocationsInstancesList: t.func = ...
    projectsLocationsInstancesImport: t.func = ...
    projectsLocationsInstancesExport: t.func = ...
    projectsLocationsInstancesCreate: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_redis() -> Import: ...
