from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    SeatsIn: t.typedef = ...
    SeatsOut: t.typedef = ...
    PrimaryAdminIn: t.typedef = ...
    PrimaryAdminOut: t.typedef = ...
    SubscriptionsIn: t.typedef = ...
    SubscriptionsOut: t.typedef = ...
    ResellernotifyResourceIn: t.typedef = ...
    ResellernotifyResourceOut: t.typedef = ...
    CustomerIn: t.typedef = ...
    CustomerOut: t.typedef = ...
    ChangePlanRequestIn: t.typedef = ...
    ChangePlanRequestOut: t.typedef = ...
    ResellernotifyGetwatchdetailsResponseIn: t.typedef = ...
    ResellernotifyGetwatchdetailsResponseOut: t.typedef = ...
    SubscriptionIn: t.typedef = ...
    SubscriptionOut: t.typedef = ...
    AddressIn: t.typedef = ...
    AddressOut: t.typedef = ...
    RenewalSettingsIn: t.typedef = ...
    RenewalSettingsOut: t.typedef = ...

class FuncList:
    customersInsert: t.func = ...
    customersPatch: t.func = ...
    customersUpdate: t.func = ...
    customersGet: t.func = ...
    resellernotifyGetwatchdetails: t.func = ...
    resellernotifyRegister: t.func = ...
    resellernotifyUnregister: t.func = ...
    subscriptionsDelete: t.func = ...
    subscriptionsChangeSeats: t.func = ...
    subscriptionsGet: t.func = ...
    subscriptionsInsert: t.func = ...
    subscriptionsChangeRenewalSettings: t.func = ...
    subscriptionsList: t.func = ...
    subscriptionsActivate: t.func = ...
    subscriptionsStartPaidService: t.func = ...
    subscriptionsChangePlan: t.func = ...
    subscriptionsSuspend: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_reseller() -> Import: ...
