from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GoogleAdsSearchads360V0Common__GenderInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__GenderInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomerClientIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomerClientOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__MaximizeConversionsIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__MaximizeConversionsOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignBudgetIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignBudgetOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__ListCustomColumnsResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__ListCustomColumnsResponseOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors__ErrorDetailsIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors__ErrorDetailsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360TextAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360TextAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupAudienceViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupAudienceViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ResponsiveSearchAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ResponsiveSearchAdInfoOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources__CampaignLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__MetricsIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__MetricsOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__LabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__LabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetRoasIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetRoasOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360FieldsRequestIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360FieldsRequestOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__DeviceInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__DeviceInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__LocationViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__LocationViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__CustomParameterIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__CustomParameterOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomerIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomerOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__MobileAppAssetIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__MobileAppAssetOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__PercentCpcIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__PercentCpcOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__ManualCpmIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__ManualCpmOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AssetIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AssetOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_DynamicSearchAdsSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_DynamicSearchAdsSettingOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_ConversionAction_ValueSettingsIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_ValueSettingsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetImpressionShareIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetImpressionShareOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__BiddingStrategyIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__BiddingStrategyOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorLocation_FieldPathElementIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors_ErrorLocation_FieldPathElementOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ProductAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ProductAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__WebpageConditionInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__WebpageConditionInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ExpandedTextAdInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ExpandedTextAdInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__SearchAds360FieldIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__SearchAds360FieldOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__ConversionActionIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__ConversionActionOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AssetSetIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AssetSetOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__DoubleClickCampaignManagerSettingIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources__DoubleClickCampaignManagerSettingOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Services__SearchAds360RowIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchAds360RowOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_TrackingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_TrackingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors__SearchAds360ErrorIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors__SearchAds360ErrorOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__GenderViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__GenderViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_NetworkSettingsIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_NetworkSettingsOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__ListAccessibleCustomersResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__ListAccessibleCustomersResponseOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__SegmentsIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__SegmentsOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignAudienceViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignAudienceViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__KeywordInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__KeywordInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__ListingGroupInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__ListingGroupInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_SelectiveOptimizationIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_SelectiveOptimizationOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupCriterionIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupCriterionOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupBidModifierIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupBidModifierOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__EnhancedCpcIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__EnhancedCpcOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360ResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360ResponseOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__AgeRangeInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__AgeRangeInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterion_QualityInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_AdGroupCriterion_QualityInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__FrequencyCapEntryIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__FrequencyCapEntryOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__KeywordViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__KeywordViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetSpendIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetSpendOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignCriterionIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CampaignCriterionOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TextLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TextLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_AttributionModelSettingsIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_ConversionAction_AttributionModelSettingsOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common__LanguageInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__LanguageInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors__QuotaErrorDetailsIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors__QuotaErrorDetailsOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetRestrictionIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetRestrictionOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_ShoppingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_ShoppingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__ConversionTrackingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__ConversionTrackingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__ValueIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__ValueOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomColumnIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomColumnOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__DynamicSearchAdsSearchTermViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__DynamicSearchAdsSearchTermViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_GeoTargetTypeSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_GeoTargetTypeSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors__ErrorCodeIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors__ErrorCodeOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__SearchAds360ExpandedDynamicSearchAdInfoIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common__SearchAds360ExpandedDynamicSearchAdInfoOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Errors__SearchAds360FailureIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors__SearchAds360FailureOut: t.typedef = ...
    GoogleAdsSearchads360V0Errors__ErrorLocationIn: t.typedef = ...
    GoogleAdsSearchads360V0Errors__ErrorLocationOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__CustomColumnHeaderIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__CustomColumnHeaderOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__LocationInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__LocationInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__UserListIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__UserListOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_OptimizationGoalSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources_Campaign_OptimizationGoalSettingOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Common__KeywordIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__KeywordOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources_ConversionAction_FloodlightSettingsIn: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources_ConversionAction_FloodlightSettingsOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources__WebpageViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__WebpageViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__LocationGroupInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__LocationGroupInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupAdLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupAdLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetCpaIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetCpaOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupAdIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupAdOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomerManagerLinkIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__CustomerManagerLinkOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__MaximizeConversionValueIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__MaximizeConversionValueOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetCpmIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetCpmOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360RequestIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360RequestOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AgeRangeViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AgeRangeViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__ManualCpaIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__ManualCpaOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__UserListInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__UserListInfoOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetOutrankShareIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__TargetOutrankShareOut: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupCriterionLabelIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__AdGroupCriterionLabelOut: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360FieldsResponseIn: t.typedef = ...
    GoogleAdsSearchads360V0Services__SearchSearchAds360FieldsResponseOut: t.typedef = (
        ...
    )
    GoogleAdsSearchads360V0Resources__ProductGroupViewIn: t.typedef = ...
    GoogleAdsSearchads360V0Resources__ProductGroupViewOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__ManualCpcIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__ManualCpcOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__RealTimeBiddingSettingIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__RealTimeBiddingSettingOut: t.typedef = ...
    GoogleAdsSearchads360V0Common__WebpageInfoIn: t.typedef = ...
    GoogleAdsSearchads360V0Common__WebpageInfoOut: t.typedef = ...

class FuncList:
    customersListAccessibleCustomers: t.func = ...
    customersSearchAds360Search: t.func = ...
    customersCustomColumnsGet: t.func = ...
    customersCustomColumnsList: t.func = ...
    searchAds360FieldsSearch: t.func = ...
    searchAds360FieldsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_searchads360() -> Import: ...
