from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    OrgPolicyViolationInfoIn: t.typedef = ...
    OrgPolicyViolationInfoOut: t.typedef = ...
    ReportResponseIn: t.typedef = ...
    ReportResponseOut: t.typedef = ...
    CheckRequestIn: t.typedef = ...
    CheckRequestOut: t.typedef = ...
    RequestMetadataIn: t.typedef = ...
    RequestMetadataOut: t.typedef = ...
    CheckResponseIn: t.typedef = ...
    CheckResponseOut: t.typedef = ...
    RequestIn: t.typedef = ...
    RequestOut: t.typedef = ...
    ServiceAccountDelegationInfoIn: t.typedef = ...
    ServiceAccountDelegationInfoOut: t.typedef = ...
    AuthorizationInfoIn: t.typedef = ...
    AuthorizationInfoOut: t.typedef = ...
    AuditLogIn: t.typedef = ...
    AuditLogOut: t.typedef = ...
    PolicyViolationInfoIn: t.typedef = ...
    PolicyViolationInfoOut: t.typedef = ...
    AuthIn: t.typedef = ...
    AuthOut: t.typedef = ...
    ResourceInfoIn: t.typedef = ...
    ResourceInfoOut: t.typedef = ...
    FirstPartyPrincipalIn: t.typedef = ...
    FirstPartyPrincipalOut: t.typedef = ...
    ThirdPartyPrincipalIn: t.typedef = ...
    ThirdPartyPrincipalOut: t.typedef = ...
    ReportRequestIn: t.typedef = ...
    ReportRequestOut: t.typedef = ...
    PeerIn: t.typedef = ...
    PeerOut: t.typedef = ...
    ViolationInfoIn: t.typedef = ...
    ViolationInfoOut: t.typedef = ...
    SpanContextIn: t.typedef = ...
    SpanContextOut: t.typedef = ...
    AuthenticationInfoIn: t.typedef = ...
    AuthenticationInfoOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    AttributeContextIn: t.typedef = ...
    AttributeContextOut: t.typedef = ...
    ApiIn: t.typedef = ...
    ApiOut: t.typedef = ...
    V2LogEntryIn: t.typedef = ...
    V2LogEntryOut: t.typedef = ...
    V2LogEntrySourceLocationIn: t.typedef = ...
    V2LogEntrySourceLocationOut: t.typedef = ...
    V2LogEntryOperationIn: t.typedef = ...
    V2LogEntryOperationOut: t.typedef = ...
    ResponseIn: t.typedef = ...
    ResponseOut: t.typedef = ...
    V2HttpRequestIn: t.typedef = ...
    V2HttpRequestOut: t.typedef = ...
    ResourceLocationIn: t.typedef = ...
    ResourceLocationOut: t.typedef = ...
    ResourceIn: t.typedef = ...
    ResourceOut: t.typedef = ...

class FuncList:
    servicesReport: t.func = ...
    servicesCheck: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_servicecontrol() -> Import: ...
