from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    PhotoResponseIn: t.typedef = ...
    PhotoResponseOut: t.typedef = ...
    PlaceIn: t.typedef = ...
    PlaceOut: t.typedef = ...
    PhotoIn: t.typedef = ...
    PhotoOut: t.typedef = ...
    BatchUpdatePhotosRequestIn: t.typedef = ...
    BatchUpdatePhotosRequestOut: t.typedef = ...
    LatLngBoundsIn: t.typedef = ...
    LatLngBoundsOut: t.typedef = ...
    Measurement3dIn: t.typedef = ...
    Measurement3dOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    PoseIn: t.typedef = ...
    PoseOut: t.typedef = ...
    UpdatePhotoRequestIn: t.typedef = ...
    UpdatePhotoRequestOut: t.typedef = ...
    ImuIn: t.typedef = ...
    ImuOut: t.typedef = ...
    GpsDataGapFailureDetailsIn: t.typedef = ...
    GpsDataGapFailureDetailsOut: t.typedef = ...
    ListPhotoSequencesResponseIn: t.typedef = ...
    ListPhotoSequencesResponseOut: t.typedef = ...
    LevelIn: t.typedef = ...
    LevelOut: t.typedef = ...
    BatchUpdatePhotosResponseIn: t.typedef = ...
    BatchUpdatePhotosResponseOut: t.typedef = ...
    NoOverlapGpsFailureDetailsIn: t.typedef = ...
    NoOverlapGpsFailureDetailsOut: t.typedef = ...
    LatLngIn: t.typedef = ...
    LatLngOut: t.typedef = ...
    InsufficientGpsFailureDetailsIn: t.typedef = ...
    InsufficientGpsFailureDetailsOut: t.typedef = ...
    PhotoSequenceIn: t.typedef = ...
    PhotoSequenceOut: t.typedef = ...
    ImuDataGapFailureDetailsIn: t.typedef = ...
    ImuDataGapFailureDetailsOut: t.typedef = ...
    ProcessingFailureDetailsIn: t.typedef = ...
    ProcessingFailureDetailsOut: t.typedef = ...
    UploadRefIn: t.typedef = ...
    UploadRefOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    BatchGetPhotosResponseIn: t.typedef = ...
    BatchGetPhotosResponseOut: t.typedef = ...
    BatchDeletePhotosRequestIn: t.typedef = ...
    BatchDeletePhotosRequestOut: t.typedef = ...
    ConnectionIn: t.typedef = ...
    ConnectionOut: t.typedef = ...
    PhotoIdIn: t.typedef = ...
    PhotoIdOut: t.typedef = ...
    NotOutdoorsFailureDetailsIn: t.typedef = ...
    NotOutdoorsFailureDetailsOut: t.typedef = ...
    BatchDeletePhotosResponseIn: t.typedef = ...
    BatchDeletePhotosResponseOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    ListPhotosResponseIn: t.typedef = ...
    ListPhotosResponseOut: t.typedef = ...

class FuncList:
    photoSequenceCreate: t.func = ...
    photoSequenceStartUpload: t.func = ...
    photoSequenceDelete: t.func = ...
    photoSequenceGet: t.func = ...
    photoSequencesList: t.func = ...
    photoGet: t.func = ...
    photoCreate: t.func = ...
    photoStartUpload: t.func = ...
    photoDelete: t.func = ...
    photoUpdate: t.func = ...
    photosList: t.func = ...
    photosBatchGet: t.func = ...
    photosBatchDelete: t.func = ...
    photosBatchUpdate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_streetviewpublish() -> Import: ...
