from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    CrowdStrikeAgentIn: t.typedef = ...
    CrowdStrikeAgentOut: t.typedef = ...
    DeviceSignalsIn: t.typedef = ...
    DeviceSignalsOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    VerifyChallengeResponseResultIn: t.typedef = ...
    VerifyChallengeResponseResultOut: t.typedef = ...
    ChallengeIn: t.typedef = ...
    ChallengeOut: t.typedef = ...
    VerifyChallengeResponseRequestIn: t.typedef = ...
    VerifyChallengeResponseRequestOut: t.typedef = ...

class FuncList:
    challengeVerify: t.func = ...
    challengeGenerate: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_verifiedaccess() -> Import: ...
