from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ListPlatformsResponseIn: t.typedef = ...
    ListPlatformsResponseOut: t.typedef = ...
    ListReleasesResponseIn: t.typedef = ...
    ListReleasesResponseOut: t.typedef = ...
    ChannelIn: t.typedef = ...
    ChannelOut: t.typedef = ...
    ListVersionsResponseIn: t.typedef = ...
    ListVersionsResponseOut: t.typedef = ...
    ListChannelsResponseIn: t.typedef = ...
    ListChannelsResponseOut: t.typedef = ...
    VersionIn: t.typedef = ...
    VersionOut: t.typedef = ...
    ReleaseIn: t.typedef = ...
    ReleaseOut: t.typedef = ...
    PlatformIn: t.typedef = ...
    PlatformOut: t.typedef = ...
    IntervalIn: t.typedef = ...
    IntervalOut: t.typedef = ...

class FuncList:
    platformsList: t.func = ...
    platformsChannelsList: t.func = ...
    platformsChannelsVersionsList: t.func = ...
    platformsChannelsVersionsReleasesList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_versionhistory() -> Import: ...
