from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    StopWorkstationRequestIn: t.typedef = ...
    StopWorkstationRequestOut: t.typedef = ...
    ListWorkstationsResponseIn: t.typedef = ...
    ListWorkstationsResponseOut: t.typedef = ...
    GceInstanceIn: t.typedef = ...
    GceInstanceOut: t.typedef = ...
    ListWorkstationClustersResponseIn: t.typedef = ...
    ListWorkstationClustersResponseOut: t.typedef = ...
    ExprIn: t.typedef = ...
    ExprOut: t.typedef = ...
    WorkstationClusterIn: t.typedef = ...
    WorkstationClusterOut: t.typedef = ...
    WorkstationConfigIn: t.typedef = ...
    WorkstationConfigOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    CustomerEncryptionKeyIn: t.typedef = ...
    CustomerEncryptionKeyOut: t.typedef = ...
    ListUsableWorkstationConfigsResponseIn: t.typedef = ...
    ListUsableWorkstationConfigsResponseOut: t.typedef = ...
    GceConfidentialInstanceConfigIn: t.typedef = ...
    GceConfidentialInstanceConfigOut: t.typedef = ...
    PrivateClusterConfigIn: t.typedef = ...
    PrivateClusterConfigOut: t.typedef = ...
    AuditConfigIn: t.typedef = ...
    AuditConfigOut: t.typedef = ...
    ListUsableWorkstationsResponseIn: t.typedef = ...
    ListUsableWorkstationsResponseOut: t.typedef = ...
    BindingIn: t.typedef = ...
    BindingOut: t.typedef = ...
    ContainerIn: t.typedef = ...
    ContainerOut: t.typedef = ...
    GoogleProtobufEmptyIn: t.typedef = ...
    GoogleProtobufEmptyOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    GceRegionalPersistentDiskIn: t.typedef = ...
    GceRegionalPersistentDiskOut: t.typedef = ...
    WorkstationIn: t.typedef = ...
    WorkstationOut: t.typedef = ...
    TestIamPermissionsResponseIn: t.typedef = ...
    TestIamPermissionsResponseOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...
    AuditLogConfigIn: t.typedef = ...
    AuditLogConfigOut: t.typedef = ...
    ListWorkstationConfigsResponseIn: t.typedef = ...
    ListWorkstationConfigsResponseOut: t.typedef = ...
    GenerateAccessTokenRequestIn: t.typedef = ...
    GenerateAccessTokenRequestOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    StartWorkstationRequestIn: t.typedef = ...
    StartWorkstationRequestOut: t.typedef = ...
    HostIn: t.typedef = ...
    HostOut: t.typedef = ...
    GceShieldedInstanceConfigIn: t.typedef = ...
    GceShieldedInstanceConfigOut: t.typedef = ...
    PersistentDirectoryIn: t.typedef = ...
    PersistentDirectoryOut: t.typedef = ...
    SetIamPolicyRequestIn: t.typedef = ...
    SetIamPolicyRequestOut: t.typedef = ...
    CancelOperationRequestIn: t.typedef = ...
    CancelOperationRequestOut: t.typedef = ...
    ReadinessCheckIn: t.typedef = ...
    ReadinessCheckOut: t.typedef = ...
    GenerateAccessTokenResponseIn: t.typedef = ...
    GenerateAccessTokenResponseOut: t.typedef = ...
    AcceleratorIn: t.typedef = ...
    AcceleratorOut: t.typedef = ...
    PolicyIn: t.typedef = ...
    PolicyOut: t.typedef = ...
    TestIamPermissionsRequestIn: t.typedef = ...
    TestIamPermissionsRequestOut: t.typedef = ...

class FuncList:
    projectsLocationsWorkstationClustersGet: t.func = ...
    projectsLocationsWorkstationClustersList: t.func = ...
    projectsLocationsWorkstationClustersDelete: t.func = ...
    projectsLocationsWorkstationClustersPatch: t.func = ...
    projectsLocationsWorkstationClustersCreate: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsCreate: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsSetIamPolicy: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsPatch: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsList: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsDelete: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsGet: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsListUsable: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsGetIamPolicy: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsTestIamPermissions: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsSetIamPolicy: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsGenerateAccessToken: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsTestIamPermissions: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsListUsable: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsStop: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsCreate: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsList: t.func = ...
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsGetIamPolicy: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsPatch: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsDelete: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsStart: t.func = (
        ...
    )
    projectsLocationsWorkstationClustersWorkstationConfigsWorkstationsGet: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsCancel: t.func = ...
    projectsLocationsOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_workstations() -> Import: ...
