from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    StackTraceElementIn: t.typedef = ...
    StackTraceElementOut: t.typedef = ...
    StateErrorIn: t.typedef = ...
    StateErrorOut: t.typedef = ...
    StackTraceIn: t.typedef = ...
    StackTraceOut: t.typedef = ...
    CancelExecutionRequestIn: t.typedef = ...
    CancelExecutionRequestOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    ErrorIn: t.typedef = ...
    ErrorOut: t.typedef = ...
    PositionIn: t.typedef = ...
    PositionOut: t.typedef = ...
    StepIn: t.typedef = ...
    StepOut: t.typedef = ...
    ExecutionIn: t.typedef = ...
    ExecutionOut: t.typedef = ...
    PubsubMessageIn: t.typedef = ...
    PubsubMessageOut: t.typedef = ...
    TriggerPubsubExecutionRequestIn: t.typedef = ...
    TriggerPubsubExecutionRequestOut: t.typedef = ...
    ListExecutionsResponseIn: t.typedef = ...
    ListExecutionsResponseOut: t.typedef = ...

class FuncList:
    projectsLocationsWorkflowsTriggerPubsubExecution: t.func = ...
    projectsLocationsWorkflowsExecutionsGet: t.func = ...
    projectsLocationsWorkflowsExecutionsCancel: t.func = ...
    projectsLocationsWorkflowsExecutionsCreate: t.func = ...
    projectsLocationsWorkflowsExecutionsList: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_workflowexecutions() -> Import: ...
