from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    ListLocationsResponseIn: t.typedef = ...
    ListLocationsResponseOut: t.typedef = ...
    WorkflowIn: t.typedef = ...
    WorkflowOut: t.typedef = ...
    EmptyIn: t.typedef = ...
    EmptyOut: t.typedef = ...
    StateErrorIn: t.typedef = ...
    StateErrorOut: t.typedef = ...
    LocationIn: t.typedef = ...
    LocationOut: t.typedef = ...
    OperationIn: t.typedef = ...
    OperationOut: t.typedef = ...
    ListOperationsResponseIn: t.typedef = ...
    ListOperationsResponseOut: t.typedef = ...
    StatusIn: t.typedef = ...
    StatusOut: t.typedef = ...
    ListWorkflowsResponseIn: t.typedef = ...
    ListWorkflowsResponseOut: t.typedef = ...
    OperationMetadataIn: t.typedef = ...
    OperationMetadataOut: t.typedef = ...

class FuncList:
    projectsLocationsList: t.func = ...
    projectsLocationsGet: t.func = ...
    projectsLocationsWorkflowsDelete: t.func = ...
    projectsLocationsWorkflowsCreate: t.func = ...
    projectsLocationsWorkflowsGet: t.func = ...
    projectsLocationsWorkflowsList: t.func = ...
    projectsLocationsWorkflowsPatch: t.func = ...
    projectsLocationsOperationsList: t.func = ...
    projectsLocationsOperationsDelete: t.func = ...
    projectsLocationsOperationsGet: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_workflows() -> Import: ...
