from typegraph import t

class TypeList:
    ErrorResponse: t.typedef = ...
    GroupContentDetailsIn: t.typedef = ...
    GroupContentDetailsOut: t.typedef = ...
    GroupItemResourceIn: t.typedef = ...
    GroupItemResourceOut: t.typedef = ...
    QueryResponseIn: t.typedef = ...
    QueryResponseOut: t.typedef = ...
    ResultTableColumnHeaderIn: t.typedef = ...
    ResultTableColumnHeaderOut: t.typedef = ...
    GroupSnippetIn: t.typedef = ...
    GroupSnippetOut: t.typedef = ...
    ListGroupItemsResponseIn: t.typedef = ...
    ListGroupItemsResponseOut: t.typedef = ...
    ListGroupsResponseIn: t.typedef = ...
    ListGroupsResponseOut: t.typedef = ...
    EmptyResponseIn: t.typedef = ...
    EmptyResponseOut: t.typedef = ...
    ErrorsIn: t.typedef = ...
    ErrorsOut: t.typedef = ...
    GroupItemIn: t.typedef = ...
    GroupItemOut: t.typedef = ...
    GroupIn: t.typedef = ...
    GroupOut: t.typedef = ...
    ErrorProtoIn: t.typedef = ...
    ErrorProtoOut: t.typedef = ...

class FuncList:
    groupsUpdate: t.func = ...
    groupsDelete: t.func = ...
    groupsInsert: t.func = ...
    groupsList: t.func = ...
    groupItemsDelete: t.func = ...
    groupItemsInsert: t.func = ...
    groupItemsList: t.func = ...
    reportsQuery: t.func = ...

class Import:
    types: TypeList = ...
    functions: FuncList = ...

def import_youtubeAnalytics() -> Import: ...
